import test from "node:test";
import assert from "node:assert/strict";
import crypto from "node:crypto";
import { copyFile, mkdir, mkdtemp, readFile, rm, symlink, writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { buildGenerationContext } from "../lib/stage3/context.js";
import { generateTemplatePitch, validateGeneratedPitch } from "../lib/stage3/isolatedPitchWorker.js";
import { persistLocalPreview, readLocalPreview } from "../lib/stage3/localPreview.js";
import { assertAllowedOutputPaths, getGenerationAdapter, listGenerationAdapters, requireGenerationAdapter, safeSlug } from "../lib/stage3/registry.js";
import { MemoryStage3Repository } from "../lib/stage3/memoryRepository.js";
import { ArtifactAutomationService } from "../lib/stage3/service.js";
import { authenticateGenerationWorker } from "../lib/stage3/workerAuth.js";

const root=path.join(path.dirname(fileURLToPath(import.meta.url)),"..","..");
const nowValues=()=>{let n=0;return()=>new Date(Date.UTC(2026,7,14,12,0,n++));};
function ids(){let n=0;return(type)=>`${type}_stage3_${++n}`;}
function seed(){return{companies:[{id:"company_a",teamId:"team_a",tenantId:"tenant_a",displayName:"Acme Works",websiteUrl:"https://acme.test",normalizedDomain:"acme.test",industry:"Manufacturing",city:"Toronto",country:"CA"},{id:"company_b",teamId:"team_b",displayName:"Foreign Co"}],contacts:[{id:"contact_a",teamId:"team_a",companyId:"company_a",fullName:"Ada Buyer",firstName:"Ada",title:"VP Growth",email:"ada@acme.test"}],opportunities:[{id:"opportunity_a",teamId:"team_a",tenantId:"tenant_a",companyId:"company_a",primaryContactId:"contact_a",contactIds:["contact_a"],name:"Acme digital overhaul",stage:"qualified",status:"open",approachAngle:"Lead with the gap between Acme's operational reputation and its dated website.",entryOffer:"Digital presence teardown",offer:"Website and systems overhaul"},{id:"opportunity_b",teamId:"team_b",companyId:"company_b",name:"Foreign"}],research:[{id:"research_verified",teamId:"team_a",companyId:"company_a",opportunityId:"opportunity_a",content:"Acme publishes a national distributor directory.",sourceUrl:"https://acme.test/distributors",sourceType:"website",verificationStatus:"verified",capturedAt:"2026-08-14T00:00:00.000Z",authorType:"user"},{id:"research_import",teamId:"team_a",companyId:"company_a",opportunityId:"opportunity_a",content:"Possible expansion initiative.",sourceType:"import",verificationStatus:"unverified",authorType:"user"}],messages:[{id:"message_a",teamId:"team_a",tenantId:"tenant_a",opportunityId:"opportunity_a",contactId:"contact_a",subject:"Acme idea",renderedSubject:"Acme idea",renderedBody:"Original approved copy",approvedSubject:"Acme idea",approvedBody:"Original approved copy",approvedContentHash:"old",approvedRecipientEmail:"ada@acme.test",approvedSenderEmail:"hello@dgtl.test",approvedBy:"owner_a",approvedAt:"2026-08-14T00:00:00.000Z",status:"approved",queueState:"not_queued",personalizationContext:{}}]};}
function service(repository,role="owner",actorId=`${role}_a`){repository.__testIdFactory||=ids();return new ArtifactAutomationService({teamId:"team_a",actor:{id:actorId,role},repository,now:nowValues(),idFactory:repository.__testIdFactory,sourceCommit:"4076f44073fb7e6597334d5f9ae9e42ba1ad7001"});}

test("adapter registry reflects real engine capability without inventing audit/report automation",()=>{const adapters=listGenerationAdapters();assert.equal(getGenerationAdapter("pitch.pages").sourceDirectory,"engine/dgtl-pitch-pages");assert.equal(getGenerationAdapter("pitch.composer").availability,"supported");assert.equal(getGenerationAdapter("audit.digital").availability,"installed_unavailable");assert.equal(getGenerationAdapter("report.client").availability,"installed_unavailable");assert.throws(()=>requireGenerationAdapter("audit.digital","audit"),/external skill/);assert.equal(adapters.filter(a=>a.artifactKinds.includes("pitch")&&a.availability==="supported").length,2);});

test("context snapshot distinguishes verified research, imports, and strategy and is immutable by copy",async()=>{const repo=new MemoryStage3Repository(seed());const graph=await repo.getOpportunityGraph("opportunity_a","team_a");const context=buildGenerationContext(graph);assert.equal(context.research[0].provenanceClass,"verified_research");assert.equal(context.research[1].provenanceClass,"imported_unverified_note");graph.opportunity.approachAngle="changed later";assert.match(context.opportunity.approachAngle,/operational reputation/);});

test("slug and output allow-lists reject traversal, arbitrary files, and adapter tampering",()=>{const adapter=getGenerationAdapter("pitch.pages");assert.equal(safeSlug("acme-overhaul"),"acme-overhaul");for(const value of ["../acme","/acme","Acme Space"])assert.throws(()=>safeSlug(value));assert.throws(()=>assertAllowedOutputPaths(adapter,"acme-overhaul",["platform/.env"]),/cannot write/);assert.throws(()=>assertAllowedOutputPaths(adapter,"acme-overhaul",["pitches/acme-overhaul/../../.env"]),/Unsafe/);assert.throws(()=>requireGenerationAdapter("shell.exec","pitch"),/Unsupported/);});

test("validation derives changed paths independently and rejects undeclared workspace writes",async()=>{const job={adapterId:"pitch.pages",slug:"acme-overhaul"};const outputManifest={paths:["pitches/acme-overhaul/index.html","pitches/acme-overhaul/pitch.json","pitches/pitches.index.json"]};await assert.rejects(()=>validateGeneratedPitch(job,{workspaceRoot:"/unused",outputManifest,changedPathsRunner:()=>[...outputManifest.paths,"platform/.env"]}),/cannot write/);});

test("validated local preview storage is fixed-root, authenticated-route addressed, and byte exact",async(t)=>{const workspace=await mkdtemp(path.join(os.tmpdir(),"dgtl-stage3-preview-workspace-"));const previewRoot=await mkdtemp(path.join(os.tmpdir(),"dgtl-stage3-preview-root-"));const outside=path.join(os.tmpdir(),`dgtl-stage3-preview-outside-${crypto.randomUUID()}.html`);t.after(()=>Promise.all([rm(workspace,{recursive:true,force:true}),rm(previewRoot,{recursive:true,force:true}),rm(outside,{force:true})]));await mkdir(path.join(workspace,"pitches","preview-test"),{recursive:true});const html="<!doctype html><h1>Sandboxed fixture</h1>";await writeFile(path.join(workspace,"pitches","preview-test","index.html"),html);const stored=await persistLocalPreview({id:"generation_job_preview",teamId:"team_a"},{workspaceRoot:workspace,outputManifest:{sourcePath:"pitches/preview-test/index.html"},previewRoot});assert.equal(stored.reference,"/api/core/generation-jobs/generation_job_preview/preview");assert.equal((await readLocalPreview("team_a","generation_job_preview",{previewRoot})).toString(),html);await assert.rejects(()=>persistLocalPreview({id:"generation_job_preview",teamId:"team_a"},{workspaceRoot:workspace,outputManifest:{sourcePath:"../outside.html"},previewRoot}),/escapes/);await writeFile(outside,html);await symlink(outside,path.join(workspace,"pitches","preview-test","linked.html"));await assert.rejects(()=>persistLocalPreview({id:"generation_job_preview",teamId:"team_a"},{workspaceRoot:workspace,outputManifest:{sourcePath:"pitches/preview-test/linked.html"},previewRoot}),/regular HTML file/);});

test("full pitch lifecycle preserves v1, creates v2, attaches exact version, and is retry-idempotent",async(t)=>{const repo=new MemoryStage3Repository(seed());const sales=service(repo,"sales","sales_a");const owner=service(repo,"owner","owner_a");const worker={id:"worker_a"};
  const requested=await sales.requestGeneration({opportunityId:"opportunity_a",artifactKind:"pitch",adapterId:"pitch.pages",slug:"acme-overhaul",selectedResearchIds:["research_verified","research_import"],instructions:"Use only verified facts as claims.",intendedCta:"Book a discovery call"});assert.equal(requested.status,"draft");assert.equal(requested.contextSnapshot.research.length,2);
  const duplicate=await sales.requestGeneration({opportunityId:"opportunity_a",artifactKind:"pitch",adapterId:"pitch.pages",slug:"acme-overhaul",selectedResearchIds:["research_verified"]});assert.equal(duplicate.id,requested.id);
  await sales.approveInput(requested.id);const claimed=await owner.claimJob(worker);assert.equal(claimed.id,requested.id);await owner.heartbeatJob(claimed.id,worker,{status:"running"});
  const temp=await mkdtemp(path.join(os.tmpdir(),"dgtl-stage3-test-"));t.after(()=>rm(temp,{recursive:true,force:true}));await mkdir(path.join(temp,"pitches","_templates"),{recursive:true});await copyFile(path.join(root,"pitches","_templates","website-overhaul.html"),path.join(temp,"pitches","_templates","website-overhaul.html"));await writeFile(path.join(temp,"pitches","pitches.index.json"),JSON.stringify({updated:"2026-08-14",pitches:[],templates:[]}));
  const output=await generateTemplatePitch(claimed,{workspaceRoot:temp});const validated=await validateGeneratedPitch(claimed,{workspaceRoot:temp,outputManifest:{...output,sourceCommit:"fixture-commit-v1"},linkCheckRunner:()=>"checked=3 missing=0 pending=0 root_absolute=0",changedPathsRunner:()=>output.paths});assert.equal(validated.validationResults.passed,true);const pending=await owner.submitResult(claimed.id,worker,{...validated,executionReference:"isolated-worktree-1",previewReference:"https://preview.invalid/acme-v1/"});assert.equal(pending.status,"awaiting_review");
  const v1=await owner.approveArtifact(claimed.id);assert.equal(v1.versionNumber,1);assert.equal((await owner.approveArtifact(claimed.id)).id,v1.id);
  const deployment=await owner.requestDeployment(v1.id,{});const claimedDeployment=await owner.claimDeployment(worker);assert.equal(claimedDeployment.id,deployment.id);await owner.completeDeployment(deployment.id,worker,{verified:true,deployedChecksum:v1.contentChecksum,deploymentUrl:"https://preview.invalid/acme-v1/",deploymentReference:"preview-v1",verificationResults:{status:200,checksumMatched:true}});
  const link=await sales.attachArtifactToMessage("message_a",v1.id);assert.equal(link.artifactVersion,1);assert.equal((await repo.getMessage("message_a","team_a")).status,"draft");
  const revision=await sales.requestRevision(v1.id,"Lead with the distributor-network proof earlier.");await sales.approveInput(revision.id);const claimed2=await owner.claimJob(worker);const checksum2="b".repeat(64);await owner.submitResult(claimed2.id,worker,{contentChecksum:checksum2,outputManifest:{paths:["pitches/acme-overhaul/index.html","pitches/acme-overhaul/pitch.json","pitches/pitches.index.json"],sourcePath:"pitches/acme-overhaul/index.html",manifestReference:"pitches/acme-overhaul/pitch.json",sourceCommit:"fixture-commit-v2"},validationResults:{passed:true,checks:{all:true}},executionReference:"isolated-worktree-2",previewReference:"https://preview.invalid/acme-v2/"});const v2=await owner.approveArtifact(claimed2.id);assert.equal(v2.versionNumber,2);assert.equal(v2.previousVersionId,v1.id);assert.equal(v1.contentChecksum,link.contentChecksum);assert.equal((await repo.listMessageArtifacts("message_a","team_a"))[0].artifactId,v1.id);assert.equal((await repo.findArtifactByJob(claimed2.id,"team_a")).id,v2.id);assert.equal(repo.assets.length,2);assert.ok(repo.activities.some(a=>a.activityType==="artifact_attached_to_message"));
});

test("validation failure cannot become an Artifact and creates a human exception",async()=>{const repo=new MemoryStage3Repository(seed());const sales=service(repo,"sales");const owner=service(repo,"owner");const job=await sales.requestGeneration({opportunityId:"opportunity_a",artifactKind:"pitch",adapterId:"pitch.pages",slug:"validation-failure"});await sales.approveInput(job.id);const worker={id:"worker_a"};await owner.claimJob(worker);const failed=await owner.submitResult(job.id,worker,{contentChecksum:"a".repeat(64),outputManifest:{paths:["pitches/validation-failure/index.html","pitches/validation-failure/pitch.json","pitches/pitches.index.json"]},validationResults:{passed:false,checks:{links:false}}});assert.equal(failed.status,"validation_failed");await assert.rejects(()=>owner.approveArtifact(job.id),/validated result/);assert.equal(repo.operationExceptions[0].exceptionType,"artifact_validation_failed");});

test("expired pre-result job leases can be reclaimed without duplicate jobs",async()=>{const repo=new MemoryStage3Repository(seed());const sales=service(repo,"sales");const owner=service(repo,"owner");const job=await sales.requestGeneration({opportunityId:"opportunity_a",artifactKind:"pitch",adapterId:"pitch.pages",slug:"lease-test"});await sales.approveInput(job.id);const first=await owner.claimJob({id:"worker_one"},{leaseSeconds:30});first.leaseExpiresAt="2020-01-01T00:00:00.000Z";const second=await owner.claimJob({id:"worker_two"});assert.equal(second.id,first.id);assert.equal(second.claimedBy,"worker_two");assert.equal(repo.generationJobs.length,1);});

test("unknown deployment outcomes are quarantined and never blindly re-deployed",async()=>{const repo=new MemoryStage3Repository(seed());repo.assets.push({id:"artifact_a",teamId:"team_a",tenantId:"tenant_a",companyId:"company_a",opportunityId:"opportunity_a",kind:"pitch",slug:"acme",versionNumber:1,status:"approved",contentChecksum:"a".repeat(64)});const owner=service(repo,"owner");const deployment=await owner.requestDeployment("artifact_a",{});const worker={id:"worker_a"};await owner.claimDeployment(worker);const unknown=await owner.completeDeployment(deployment.id,worker,{outcome:"unknown",errorMetadata:{reason:"connection lost"}});assert.equal(unknown.status,"outcome_unknown");assert.equal(await owner.claimDeployment(worker),null);assert.equal(repo.operationExceptions.at(-1).exceptionType,"artifact_deployment_unknown");});

test("generation and deployment failures become terminal, reviewable exceptions",async()=>{const repo=new MemoryStage3Repository(seed());const sales=service(repo,"sales");const owner=service(repo,"owner");const worker={id:"worker_a"};const job=await sales.requestGeneration({opportunityId:"opportunity_a",artifactKind:"pitch",adapterId:"pitch.pages",slug:"worker-failure"});await sales.approveInput(job.id);await owner.claimJob(worker);const failed=await owner.failJob(job.id,worker,{code:"skill_failed",message:"Fixture generation failure",retryable:false});assert.equal(failed.status,"failed");assert.equal(repo.operationExceptions.at(-1).exceptionType,"artifact_generation_failed");
  repo.assets.push({id:"artifact_failure",teamId:"team_a",tenantId:"tenant_a",companyId:"company_a",opportunityId:"opportunity_a",kind:"pitch",slug:"deploy-failure",versionNumber:1,status:"approved",contentChecksum:"a".repeat(64)});const deployment=await owner.requestDeployment("artifact_failure",{});await owner.claimDeployment(worker);const deploymentFailed=await owner.completeDeployment(deployment.id,worker,{outcome:"failed",errorMetadata:{code:"preview_unavailable"}});assert.equal(deploymentFailed.status,"deployment_failed");assert.equal(repo.operationExceptions.at(-1).exceptionType,"artifact_deployment_failed");});

test("slug collisions, self-approval, production targets, and repeat deployments fail safely",async()=>{const repo=new MemoryStage3Repository(seed());const sales=service(repo,"sales");const owner=service(repo,"owner");const first=await sales.requestGeneration({opportunityId:"opportunity_a",artifactKind:"pitch",adapterId:"pitch.pages",slug:"reserved-slug"});await assert.rejects(()=>sales.requestGeneration({opportunityId:"opportunity_a",artifactKind:"pitch",adapterId:"pitch.pages",slug:"reserved-slug",idempotencyKey:"different-request"}),/already reserved/);await sales.approveInput(first.id);const sameIdentityWorker={id:"owner_a"};await owner.claimJob(sameIdentityWorker);await owner.submitResult(first.id,sameIdentityWorker,{contentChecksum:"a".repeat(64),outputManifest:{paths:["pitches/reserved-slug/index.html","pitches/reserved-slug/pitch.json","pitches/pitches.index.json"],sourcePath:"pitches/reserved-slug/index.html",manifestReference:"pitches/reserved-slug/pitch.json",sourceCommit:"fixture"},validationResults:{passed:true},previewReference:"https://preview.invalid/reserved-slug/"});await assert.rejects(()=>owner.approveArtifact(first.id),/cannot approve its own/);
  repo.assets.push({id:"artifact_prod",teamId:"team_a",tenantId:"tenant_a",companyId:"company_a",opportunityId:"opportunity_a",kind:"pitch",slug:"prod",versionNumber:1,status:"approved",contentChecksum:"b".repeat(64)});await assert.rejects(()=>owner.requestDeployment("artifact_prod",{adapterId:"pitch.portal",targetId:"production",productionAuthorized:true}),/unavailable/);const previewOne=await owner.requestDeployment("artifact_prod",{});const previewTwo=await owner.requestDeployment("artifact_prod",{});assert.equal(previewTwo.id,previewOne.id);assert.equal(repo.artifactDeployments.length,1);});

test("cross-team jobs, artifacts, Messages, and Opportunities remain inaccessible",async()=>{const repo=new MemoryStage3Repository(seed());const owner=service(repo,"owner");await assert.rejects(()=>owner.requestGeneration({opportunityId:"opportunity_b",artifactKind:"pitch",adapterId:"pitch.pages",slug:"foreign"}),/not found/);repo.assets.push({id:"artifact_foreign",teamId:"team_b",opportunityId:"opportunity_b",kind:"pitch",status:"deployed",deploymentUrl:"https://foreign.invalid",contentChecksum:"a".repeat(64)});await assert.rejects(()=>owner.getArtifact("artifact_foreign"),/not found/);await assert.rejects(()=>owner.attachArtifactToMessage("message_a","artifact_foreign"),/not found/);});

test("worker auth binds team and identity to server configuration, not request input",()=>{const request={headers:new Headers({authorization:"Bearer secret"})};const worker=authenticateGenerationWorker(request,{CORE_GENERATION_WORKER_TOKEN:"secret",CORE_GENERATION_WORKER_TEAM_ID:"team_a",CORE_GENERATION_WORKER_ID:"worker_a"});assert.equal(worker.teamId,"team_a");assert.equal(worker.id,"worker_a");assert.throws(()=>authenticateGenerationWorker({headers:new Headers({authorization:"Bearer wrong","x-team-id":"team_b"})},{CORE_GENERATION_WORKER_TOKEN:"secret",CORE_GENERATION_WORKER_TEAM_ID:"team_a"}),/authentication failed/);});

test("migration 012 is additive and carries version, deployment, exact Message attachment, and team constraints",async()=>{const sql=await readFile(path.join(root,"platform","migrations","012_artifact_automation_phase_3.sql"),"utf8");for(const token of ["artifact_families","artifact_deployments","message_artifacts","context_snapshot","content_checksum","lease_expires_at","foreign key (artifact_id, team_id)","generation_jobs_company_team_fkey","artifacts_previous_version_team_fkey"])assert.match(sql,new RegExp(token.replace(/[()]/g,"\\$&"),"i"));assert.doesNotMatch(sql,/drop\s+(table|column)|truncate\s|delete\s+from/i);});

test("generated preview is sandboxed and worker API never imports shell execution",async()=>{const page=await readFile(path.join(root,"platform","app","(core)","generation-jobs","[id]","page.jsx"),"utf8");assert.match(page,/sandbox=""/);const previewRoute=await readFile(path.join(root,"platform","app","api","core","generation-jobs","[id]","preview","route.js"),"utf8");assert.match(previewRoute,/content-security-policy/);assert.match(previewRoute,/Only validated output can be previewed/);const routes=(await Promise.all(["claim","heartbeat","result"].map(async name=>name))).join(" ");assert.ok(routes);const route=await readFile(path.join(root,"platform","app","api","core","generation-worker","jobs","claim","route.js"),"utf8");assert.doesNotMatch(route,/child_process|exec\(|spawn\(/);});

test("preview result references reject script and insecure transport schemes",async()=>{const repo=new MemoryStage3Repository(seed());const sales=service(repo,"sales");const owner=service(repo,"owner");const worker={id:"worker_a"};const job=await sales.requestGeneration({opportunityId:"opportunity_a",artifactKind:"pitch",adapterId:"pitch.pages",slug:"unsafe-preview"});await sales.approveInput(job.id);await owner.claimJob(worker);await assert.rejects(()=>owner.submitResult(job.id,worker,{contentChecksum:"a".repeat(64),outputManifest:{paths:["pitches/unsafe-preview/index.html","pitches/unsafe-preview/pitch.json","pitches/pitches.index.json"]},validationResults:{passed:true},previewReference:"javascript:alert(1)"}),/authenticated local preview route or an HTTPS/);});
