import { Pool } from "pg";
import { PostgresStage2Repository } from "../stage2/repository.js";

function camelKey(key){return key.replace(/_([a-z])/g,(_,letter)=>letter.toUpperCase());}
function mapRow(row){return row?Object.fromEntries(Object.entries(row).map(([key,value])=>[camelKey(key),value?.toISOString?.()||value])):null;}
const json=(value)=>JSON.stringify(value??{});

export class PostgresStage3Repository extends PostgresStage2Repository {
  async transaction(work){if(!this.db.connect)return work(this);const client=await this.db.connect();try{await client.query("begin");const result=await work(new PostgresStage3Repository(client));await client.query("commit");return result;}catch(error){await client.query("rollback");throw error;}finally{client.release();}}
  async reserveArtifactFamily(r,{revision=false}={}){const existing=mapRow((await this.db.query("select * from artifact_families where team_id=$1 and kind=$2 and slug=$3 for update",[r.teamId,r.kind,r.slug])).rows[0]);if(existing&&!revision)throw Object.assign(new Error("Artifact slug is already reserved; choose revision explicitly."),{status:409,code:"slug_collision"});if(existing)return existing;return mapRow((await this.db.query(`insert into artifact_families(id,team_id,tenant_id,company_id,opportunity_id,kind,slug,status,created_by,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *`,[r.id,r.teamId,r.tenantId||null,r.companyId,r.opportunityId,r.kind,r.slug,r.status,r.createdBy||null,r.createdAt,r.updatedAt])).rows[0]);}
  async getArtifactFamily(id,teamId){return mapRow((await this.db.query("select * from artifact_families where id=$1 and team_id=$2",[id,teamId])).rows[0]);}
  async createGenerationJob(r){return mapRow((await this.db.query(`insert into generation_jobs(id,team_id,tenant_id,company_id,opportunity_id,requested_tool,requested_skill,brief,status,created_by,error_metadata,result_metadata,created_at,updated_at,artifact_family_id,artifact_kind,adapter_id,adapter_version,source_commit,slug,context_snapshot,generation_parameters,idempotency_key,attempt_count,revision_of_job_id,revision_instructions) values($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11::jsonb,$12::jsonb,$13,$14,$15,$16,$17,$18,$19,$20,$21::jsonb,$22::jsonb,$23,$24,$25,$26) returning *`,[r.id,r.teamId,r.tenantId||null,r.companyId,r.opportunityId,r.requestedTool,r.requestedSkill,r.brief?json(r.brief):"{}",r.status,r.createdBy||null,json(r.errorMetadata),json(r.resultMetadata),r.createdAt,r.updatedAt,r.artifactFamilyId,r.artifactKind,r.adapterId,r.adapterVersion,r.sourceCommit,r.slug,json(r.contextSnapshot),json(r.generationParameters),r.idempotencyKey,r.attemptCount||0,r.revisionOfJobId||null,r.revisionInstructions||null])).rows[0]);}
  async listGenerationJobs(teamId){return(await this.db.query("select * from generation_jobs where team_id=$1 order by created_at desc",[teamId])).rows.map(mapRow);}
  async getGenerationJob(id,teamId){return mapRow((await this.db.query("select * from generation_jobs where id=$1 and team_id=$2",[id,teamId])).rows[0]);}
  async findGenerationJobByIdempotency(teamId,key){return mapRow((await this.db.query("select * from generation_jobs where team_id=$1 and idempotency_key=$2",[teamId,key])).rows[0]);}
  async updateGenerationJob(id,teamId,values,expectedStatus){const columns={status:"status",inputApprovedBy:"input_approved_by",inputApprovedAt:"input_approved_at",claimedBy:"claimed_by",claimedAt:"claimed_at",leaseExpiresAt:"lease_expires_at",heartbeatAt:"heartbeat_at",attemptCount:"attempt_count",executionReference:"execution_reference",resultMetadata:"result_metadata",validationResults:"validation_results",outputManifest:"output_manifest",contentChecksum:"content_checksum",previewReference:"preview_reference",resultSubmittedAt:"result_submitted_at",errorMetadata:"error_metadata",cancellationMetadata:"cancellation_metadata",startedAt:"started_at",completedAt:"completed_at",updatedAt:"updated_at"};const jsonFields=new Set(["resultMetadata","validationResults","outputManifest","errorMetadata","cancellationMetadata"]);const entries=Object.entries(values).filter(([key])=>columns[key]);if(!entries.length)return null;const args=entries.map(([key,value])=>jsonFields.has(key)?json(value):(value===""?null:value));const set=entries.map(([key],i)=>`${columns[key]}=$${i+1}${jsonFields.has(key)?"::jsonb":""}`).join(",");args.push(id,teamId);let where="";if(expectedStatus){const states=[].concat(expectedStatus);args.push(states);where=` and status=any($${args.length}::text[])`;}return mapRow((await this.db.query(`update generation_jobs set ${set} where id=$${entries.length+1} and team_id=$${entries.length+2}${where} returning *`,args)).rows[0]);}
  async claimGenerationJob(teamId,workerId,now,leaseExpiresAt){return mapRow((await this.db.query(`with candidate as (select id from generation_jobs where team_id=$1 and (status='queued' or (status in ('claimed','running','validating') and lease_expires_at<$3)) order by created_at for update skip locked limit 1) update generation_jobs j set status='claimed',claimed_by=$2,claimed_at=$3,heartbeat_at=$3,lease_expires_at=$4,attempt_count=j.attempt_count+1,updated_at=$3 from candidate where j.id=candidate.id returning j.*`,[teamId,workerId,now,leaseExpiresAt])).rows[0]);}
  async listArtifacts(teamId){return(await this.db.query("select * from artifacts where team_id=$1 order by created_at desc",[teamId])).rows.map(mapRow);}
  async getArtifact(id,teamId){return mapRow((await this.db.query("select * from artifacts where id=$1 and team_id=$2",[id,teamId])).rows[0]);}
  async findArtifactByJob(jobId,teamId){return mapRow((await this.db.query("select * from artifacts where generation_job_id=$1 and team_id=$2",[jobId,teamId])).rows[0]);}
  async nextArtifactVersion(familyId,teamId){return Number((await this.db.query("select coalesce(max(version_number),0)+1 version from artifacts where artifact_family_id=$1 and team_id=$2",[familyId,teamId])).rows[0].version);}
  async createArtifactVersion(r){const existing=await this.findArtifactByJob(r.generationJobId,r.teamId);if(existing)return existing;const row=mapRow((await this.db.query(`insert into artifacts(id,team_id,tenant_id,opportunity_id,company_id,generation_job_id,kind,slug,source_path,build_commit,deployment_target,deployment_url,version,status,approved_at,metadata,created_at,updated_at,artifact_family_id,previous_version_id,version_number,source_commit,content_checksum,manifest_reference,validation_status,approved_by) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16::jsonb,$17,$18,$19,$20,$21,$22,$23,$24,$25,$26) returning *`,[r.id,r.teamId,r.tenantId||null,r.opportunityId,r.companyId,r.generationJobId,r.kind,r.slug,r.sourcePath,r.buildCommit||null,r.deploymentTarget||null,r.deploymentUrl||null,String(r.versionNumber),r.status,r.approvedAt,json(r.metadata),r.createdAt,r.updatedAt,r.artifactFamilyId,r.previousVersionId||null,r.versionNumber,r.sourceCommit,r.contentChecksum,r.manifestReference,r.validationStatus,r.approvedBy])).rows[0]);await this.db.query("insert into generation_job_artifacts(generation_job_id,artifact_id) values($1,$2) on conflict do nothing",[r.generationJobId,r.id]);return row;}
  async updateArtifactDeploymentFields(id,teamId,v){return mapRow((await this.db.query("update artifacts set deployment_target=coalesce($1,deployment_target),deployment_url=coalesce($2,deployment_url),status=coalesce($3,status),updated_at=$4 where id=$5 and team_id=$6 returning *",[v.deploymentTarget||null,v.deploymentUrl||null,v.status||null,v.updatedAt,id,teamId])).rows[0]);}
  async createArtifactDeployment(r){const existing=mapRow((await this.db.query("select * from artifact_deployments where team_id=$1 and idempotency_key=$2",[r.teamId,r.idempotencyKey])).rows[0]);if(existing)return existing;return mapRow((await this.db.query(`insert into artifact_deployments(id,team_id,tenant_id,artifact_id,adapter_id,target_id,status,idempotency_key,approved_by,approved_at,requested_by,requested_at,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14) returning *`,[r.id,r.teamId,r.tenantId||null,r.artifactId,r.adapterId,r.targetId,r.status,r.idempotencyKey,r.approvedBy||null,r.approvedAt||null,r.requestedBy||null,r.requestedAt,r.createdAt,r.updatedAt])).rows[0]);}
  async listArtifactDeployments(teamId,artifactId=""){const result=artifactId?await this.db.query("select * from artifact_deployments where team_id=$1 and artifact_id=$2 order by created_at desc",[teamId,artifactId]):await this.db.query("select * from artifact_deployments where team_id=$1 order by created_at desc",[teamId]);return result.rows.map(mapRow);}
  async getArtifactDeployment(id,teamId){return mapRow((await this.db.query("select * from artifact_deployments where id=$1 and team_id=$2",[id,teamId])).rows[0]);}
  async updateArtifactDeployment(id,teamId,v,expectedStatus){const columns={status:"status",claimedBy:"claimed_by",claimedAt:"claimed_at",leaseExpiresAt:"lease_expires_at",attemptCount:"attempt_count",deploymentReference:"deployment_reference",deploymentUrl:"deployment_url",deployedChecksum:"deployed_checksum",verificationResults:"verification_results",errorMetadata:"error_metadata",uncertainAt:"uncertain_at",completedAt:"completed_at",updatedAt:"updated_at"};const jf=new Set(["verificationResults","errorMetadata"]);const entries=Object.entries(v).filter(([key])=>columns[key]);const args=entries.map(([key,value])=>jf.has(key)?json(value):(value===""?null:value));const set=entries.map(([key],i)=>`${columns[key]}=$${i+1}${jf.has(key)?"::jsonb":""}`).join(",");args.push(id,teamId);let where="";if(expectedStatus){args.push([].concat(expectedStatus));where=` and status=any($${args.length}::text[])`;}return mapRow((await this.db.query(`update artifact_deployments set ${set} where id=$${entries.length+1} and team_id=$${entries.length+2}${where} returning *`,args)).rows[0]);}
  async claimArtifactDeployment(teamId,workerId,now,leaseExpiresAt){return mapRow((await this.db.query(`with candidate as(select id from artifact_deployments where team_id=$1 and (status='deploy_queued' or(status='deploying' and lease_expires_at<$3)) order by requested_at for update skip locked limit 1) update artifact_deployments d set status='deploying',claimed_by=$2,claimed_at=$3,lease_expires_at=$4,attempt_count=d.attempt_count+1,updated_at=$3 from candidate where d.id=candidate.id returning d.*`,[teamId,workerId,now,leaseExpiresAt])).rows[0]);}
  async createMessageArtifact(r){const existing=mapRow((await this.db.query("select * from message_artifacts where message_id=$1 and artifact_id=$2",[r.messageId,r.artifactId])).rows[0]);if(existing)return existing;return mapRow((await this.db.query(`insert into message_artifacts(id,team_id,message_id,artifact_id,artifact_version,artifact_kind,artifact_title,deployment_url_snapshot,content_checksum,attached_by,attached_at) values($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11) returning *`,[r.id,r.teamId,r.messageId,r.artifactId,r.artifactVersion,r.artifactKind,r.artifactTitle||null,r.deploymentUrlSnapshot,r.contentChecksum,r.attachedBy||null,r.attachedAt])).rows[0]);}
  async listMessageArtifacts(messageId,teamId){return(await this.db.query("select * from message_artifacts where message_id=$1 and team_id=$2 order by attached_at",[messageId,teamId])).rows.map(mapRow);}
}

let pool;
export function getStage3Repository(){if(!process.env.DATABASE_URL)return null;if(!pool)pool=new Pool({connectionString:process.env.DATABASE_URL});return new PostgresStage3Repository(pool);}
export function __resetStage3RepositoryForTests(){pool=null;}
