import crypto from "node:crypto";
import { createCoreId } from "../core/ids.js";
import { buildGenerationContext, validateGenerationContext } from "./context.js";
import { assertAllowedOutputPaths, requireDeploymentAdapter, requireGenerationAdapter, safeSlug } from "./registry.js";

const iso = (value = new Date()) => new Date(value).toISOString();
const sha256 = (value) => crypto.createHash("sha256").update(String(value || "")).digest("hex");
function required(value, name){const text=String(value||"").trim();if(!text)throw Object.assign(new Error(`${name} is required.`),{status:400});return text;}
function role(actor, allowed){if(!allowed.includes(actor?.role))throw Object.assign(new Error("Forbidden."),{status:403});}
function safePreviewReference(value,jobId){const reference=required(value,"previewReference");if(reference===`/api/core/generation-jobs/${encodeURIComponent(jobId)}/preview`)return reference;try{const url=new URL(reference);if(url.protocol==="https:")return reference;}catch{}throw Object.assign(new Error("previewReference must be the authenticated local preview route or an HTTPS staging URL."),{status:400,code:"unsafe_preview_reference"});}

export class ArtifactAutomationService {
  constructor({ teamId, actor, repository, now = () => new Date(), idFactory = createCoreId, sourceCommit = process.env.DGTL_SOURCE_COMMIT || "unresolved" }) {
    this.teamId=required(teamId,"teamId");this.actor=actor||{};this.repository=repository;this.now=now;this.idFactory=idFactory;this.sourceCommit=sourceCommit;
  }
  at(){return iso(this.now());}
  async activity(input,repository=this.repository){const at=this.at();return repository.createActivity({id:this.idFactory("activity"),teamId:this.teamId,tenantId:input.tenantId||"",companyId:input.companyId||"",contactId:input.contactId||"",opportunityId:input.opportunityId||"",campaignId:input.campaignId||"",messageId:input.messageId||"",activityType:input.activityType,occurredAt:at,actorType:input.actorType||"user",actorId:input.actorId||this.actor.id||"",summary:input.summary||"",metadata:input.metadata||{},createdAt:at,updatedAt:at});}
  async exception(input){const at=this.at();return this.repository.createOperationException({id:this.idFactory("operationException"),teamId:this.teamId,exceptionType:input.exceptionType,severity:input.severity||"warning",sourceEntityType:input.sourceEntityType,sourceEntityId:input.sourceEntityId,status:"open",summary:input.summary,details:input.details||{},createdAt:at,updatedAt:at});}
  async listJobs(){return this.repository.listGenerationJobs(this.teamId);}
  async getJob(id){const job=await this.repository.getGenerationJob(id,this.teamId);if(!job)throw Object.assign(new Error("Generation job not found."),{status:404});return job;}
  async listArtifacts(){return this.repository.listArtifacts(this.teamId);}
  async getArtifact(id){const artifact=await this.repository.getArtifact(id,this.teamId);if(!artifact)throw Object.assign(new Error("Artifact not found."),{status:404});return artifact;}
  async requestGeneration(input={}){
    role(this.actor,["owner","admin","sales"]);
    const opportunityId=required(input.opportunityId,"opportunityId");
    const graph=await this.repository.getOpportunityGraph(opportunityId,this.teamId);if(!graph)throw Object.assign(new Error("Opportunity not found."),{status:404});
    const kind=required(input.artifactKind,"artifactKind");const adapter=requireGenerationAdapter(input.adapterId,kind);const slug=safeSlug(input.slug);
    const context=buildGenerationContext(graph,{selectedResearchIds:input.selectedResearchIds||[],campaign:input.campaign||null});
    if(input.approvedPitchArtifactId)context.approvedPitchArtifactId=input.approvedPitchArtifactId;
    const missing=validateGenerationContext(context,adapter);if(missing.length)throw Object.assign(new Error(`Generation context is missing: ${missing.join(", ")}.`),{status:422,code:"missing_generation_context",missing});
    const idempotencyKey=input.idempotencyKey||sha256([this.teamId,opportunityId,adapter.id,kind,slug,input.revisionOfJobId||"new"].join(":"));
    const existing=await this.repository.findGenerationJobByIdempotency(this.teamId,idempotencyKey);if(existing)return existing;
    const at=this.at();
    return this.repository.transaction(async(repo)=>{
      const family=await repo.reserveArtifactFamily({id:this.idFactory("artifactFamily"),teamId:this.teamId,tenantId:graph.opportunity.tenantId||graph.company.tenantId||"",companyId:graph.company.id,opportunityId,kind,slug,status:"active",createdBy:this.actor.id||"",createdAt:at,updatedAt:at},{revision:Boolean(input.revisionOfJobId)});
      const job=await repo.createGenerationJob({id:this.idFactory("generationJob"),teamId:this.teamId,tenantId:graph.opportunity.tenantId||graph.company.tenantId||"",companyId:graph.company.id,opportunityId,requestedTool:"generation_adapter",requestedSkill:adapter.skillName,brief:{instructions:String(input.instructions||""),intendedCta:String(input.intendedCta||""),targetContactId:String(input.targetContactId||graph.opportunity.primaryContactId||"")},status:"draft",createdBy:this.actor.id||"",errorMetadata:{},resultMetadata:{},artifactFamilyId:family.id,artifactKind:kind,adapterId:adapter.id,adapterVersion:adapter.workflowVersion,sourceCommit:this.sourceCommit,slug,contextSnapshot:context,generationParameters:{mode:String(input.generationMode||"standard"),selectedResearchIds:input.selectedResearchIds||[]},idempotencyKey,attemptCount:0,revisionOfJobId:input.revisionOfJobId||"",revisionInstructions:String(input.revisionInstructions||""),createdAt:at,updatedAt:at});
      await this.activity({tenantId:job.tenantId,companyId:job.companyId,opportunityId,activityType:"generation_requested",summary:`${adapter.displayName} brief created for review.`,metadata:{generationJobId:job.id,adapterId:adapter.id,slug}},repo);return job;
    });
  }
  async approveInput(id){role(this.actor,["owner","admin","sales"]);const at=this.at();const job=await this.repository.updateGenerationJob(id,this.teamId,{status:"queued",inputApprovedBy:this.actor.id||"",inputApprovedAt:at,updatedAt:at},"draft");if(!job)throw Object.assign(new Error("Only a draft generation brief can be approved."),{status:409});await this.activity({tenantId:job.tenantId,companyId:job.companyId,opportunityId:job.opportunityId,activityType:"generation_brief_approved",summary:"Generation context and brief approved.",metadata:{generationJobId:job.id,contentHash:sha256(JSON.stringify(job.contextSnapshot))}});return job;}
  async claimJob(worker,{leaseSeconds=300}={}){const at=this.at();const expires=iso(new Date(new Date(at).getTime()+Math.max(30,Math.min(Number(leaseSeconds)||300,900))*1000));const job=await this.repository.claimGenerationJob(this.teamId,worker.id,at,expires);if(job)await this.activity({tenantId:job.tenantId,companyId:job.companyId,opportunityId:job.opportunityId,actorType:"service",actorId:worker.id,activityType:"generation_claimed",summary:"Authorized generation worker claimed the job.",metadata:{generationJobId:job.id,leaseExpiresAt:expires}});return job;}
  async heartbeatJob(id,worker,{status="running",leaseSeconds=300}={}){const current=await this.getJob(id);if(current.claimedBy!==worker.id)throw Object.assign(new Error("Worker does not own this lease."),{status:403});if(!["claimed","running","validating"].includes(current.status))throw Object.assign(new Error("Job is not lease-active."),{status:409});const at=this.at();return this.repository.updateGenerationJob(id,this.teamId,{status,heartbeatAt:at,leaseExpiresAt:iso(new Date(new Date(at).getTime()+Math.min(Number(leaseSeconds)||300,900)*1000)),startedAt:current.startedAt||at,updatedAt:at},["claimed","running","validating"]);}
  async submitResult(id,worker,input={}){const job=await this.getJob(id);if(job.claimedBy!==worker.id)throw Object.assign(new Error("Worker does not own this job."),{status:403});if(!["claimed","running","validating"].includes(job.status))throw Object.assign(new Error("Job cannot accept a result in its current state."),{status:409});const adapter=requireGenerationAdapter(job.adapterId,job.artifactKind);const paths=input.outputManifest?.paths||[];assertAllowedOutputPaths(adapter,job.slug,paths);const checksum=required(input.contentChecksum,"contentChecksum");if(!/^[a-f0-9]{64}$/i.test(checksum))throw Object.assign(new Error("contentChecksum must be SHA-256."),{status:400});const validation=input.validationResults||{};const preview=input.previewReference?safePreviewReference(input.previewReference,id):"";const at=this.at();if(validation.passed!==true){const failed=await this.repository.updateGenerationJob(id,this.teamId,{status:"validation_failed",executionReference:String(input.executionReference||""),resultMetadata:input.resultMetadata||{},validationResults:validation,outputManifest:input.outputManifest||{},contentChecksum:checksum,previewReference:preview,resultSubmittedAt:at,completedAt:at,updatedAt:at},["claimed","running","validating"]);await this.exception({exceptionType:"artifact_validation_failed",sourceEntityType:"generation_job",sourceEntityId:id,summary:"Generated artifact failed deterministic validation.",details:{validationResults:validation}});await this.activity({tenantId:job.tenantId,companyId:job.companyId,opportunityId:job.opportunityId,actorType:"service",actorId:worker.id,activityType:"generation_validation_failed",summary:"Generated output failed validation.",metadata:{generationJobId:id}});return failed;}
    const completed=await this.repository.updateGenerationJob(id,this.teamId,{status:"awaiting_review",executionReference:String(input.executionReference||""),resultMetadata:input.resultMetadata||{},validationResults:validation,outputManifest:input.outputManifest||{},contentChecksum:checksum,previewReference:safePreviewReference(input.previewReference,id),resultSubmittedAt:at,completedAt:at,updatedAt:at},["claimed","running","validating"]);await this.activity({tenantId:job.tenantId,companyId:job.companyId,opportunityId:job.opportunityId,actorType:"service",actorId:worker.id,activityType:"generation_completed",summary:"Generated output passed validation and awaits human review.",metadata:{generationJobId:id,contentChecksum:checksum}});return completed;}
  async failJob(id,worker,input={}){const job=await this.getJob(id);if(job.claimedBy!==worker.id)throw Object.assign(new Error("Worker does not own this job."),{status:403});const at=this.at();const failed=await this.repository.updateGenerationJob(id,this.teamId,{status:"failed",errorMetadata:{code:String(input.code||"generation_failed"),message:String(input.message||"Generation worker failed."),retryable:Boolean(input.retryable)},completedAt:at,updatedAt:at},["claimed","running","validating"]);if(!failed)throw Object.assign(new Error("Job cannot be failed in its current state."),{status:409});await this.exception({exceptionType:"artifact_generation_failed",sourceEntityType:"generation_job",sourceEntityId:id,summary:"Generation requires operator review.",details:failed.errorMetadata});await this.activity({tenantId:job.tenantId,companyId:job.companyId,opportunityId:job.opportunityId,actorType:"service",actorId:worker.id,activityType:"generation_failed",summary:"Generation worker reported failure.",metadata:{generationJobId:id,code:failed.errorMetadata.code}});return failed;}
  async approveArtifact(jobId){role(this.actor,["owner","admin"]);const existing=await this.repository.findArtifactByJob(jobId,this.teamId);if(existing)return existing;const job=await this.getJob(jobId);if(job.status!=="awaiting_review"||job.validationResults?.passed!==true)throw Object.assign(new Error("Only a validated result awaiting review can be approved."),{status:409});if(job.claimedBy&&job.claimedBy===this.actor.id)throw Object.assign(new Error("A generator cannot approve its own output."),{status:403});const version=await this.repository.nextArtifactVersion(job.artifactFamilyId,this.teamId);const prior=(await this.repository.listArtifacts(this.teamId)).filter((item)=>item.artifactFamilyId===job.artifactFamilyId).sort((a,b)=>Number(b.versionNumber||0)-Number(a.versionNumber||0))[0];const at=this.at();const artifact=await this.repository.createArtifactVersion({id:this.idFactory("asset"),teamId:this.teamId,tenantId:job.tenantId,opportunityId:job.opportunityId,companyId:job.companyId,generationJobId:job.id,artifactFamilyId:job.artifactFamilyId,previousVersionId:prior?.id||"",kind:job.artifactKind,slug:job.slug,sourcePath:job.outputManifest?.sourcePath||`pitches/${job.slug}/index.html`,sourceCommit:job.outputManifest?.sourceCommit||job.sourceCommit,buildCommit:job.outputManifest?.sourceCommit||job.sourceCommit,contentChecksum:job.contentChecksum,manifestReference:job.outputManifest?.manifestReference||`pitches/${job.slug}/pitch.json`,validationStatus:"passed",versionNumber:version,status:"approved",approvedAt:at,approvedBy:this.actor.id||"",metadata:{previewReference:job.previewReference,generatedPaths:job.outputManifest?.paths||[],adapterId:job.adapterId},createdAt:at,updatedAt:at});await this.repository.updateGenerationJob(job.id,this.teamId,{status:"approved",updatedAt:at},"awaiting_review");await this.activity({tenantId:job.tenantId,companyId:job.companyId,opportunityId:job.opportunityId,activityType:"artifact_approved",summary:`Approved ${job.artifactKind} ${job.slug} v${version}.`,metadata:{generationJobId:job.id,artifactId:artifact.id,contentChecksum:artifact.contentChecksum}});return artifact;}
  async requestRevision(artifactId,instructions){role(this.actor,["owner","admin","sales"]);const artifact=await this.getArtifact(artifactId);const source=await this.getJob(artifact.generationJobId);return this.requestGeneration({opportunityId:artifact.opportunityId,artifactKind:artifact.kind,adapterId:source.adapterId,slug:artifact.slug,instructions:source.brief?.instructions||"",intendedCta:source.brief?.intendedCta||"",selectedResearchIds:source.generationParameters?.selectedResearchIds||[],revisionOfJobId:source.id,revisionInstructions:required(instructions,"revision instructions")});}
  async requestDeployment(artifactId,{adapterId="pitch.local-preview",targetId="isolated-preview",productionAuthorized=false}={}){role(this.actor,["owner","admin"]);const artifact=await this.getArtifact(artifactId);if(artifact.status!=="approved")throw Object.assign(new Error("Only an approved artifact can be deployed."),{status:409});requireDeploymentAdapter(adapterId,artifact.kind,{productionAuthorized});const at=this.at();const deployment=await this.repository.createArtifactDeployment({id:this.idFactory("artifactDeployment"),teamId:this.teamId,tenantId:artifact.tenantId,artifactId:artifact.id,adapterId,targetId,status:"deploy_queued",idempotencyKey:sha256([artifact.id,artifact.contentChecksum,adapterId,targetId].join(":")),approvedBy:this.actor.id||"",approvedAt:at,requestedBy:this.actor.id||"",requestedAt:at,createdAt:at,updatedAt:at});await this.activity({tenantId:artifact.tenantId,companyId:artifact.companyId,opportunityId:artifact.opportunityId,activityType:"artifact_deployment_requested",summary:`Approved deployment to ${targetId}.`,metadata:{artifactId:artifact.id,deploymentId:deployment.id,adapterId}});return deployment;}
  async claimDeployment(worker,{leaseSeconds=300}={}){const at=this.at();return this.repository.claimArtifactDeployment(this.teamId,worker.id,at,iso(new Date(new Date(at).getTime()+Math.min(Number(leaseSeconds)||300,900)*1000)));}
  async completeDeployment(id,worker,input={}){const deployment=await this.repository.getArtifactDeployment(id,this.teamId);if(!deployment)throw Object.assign(new Error("Deployment not found."),{status:404});if(deployment.claimedBy!==worker.id||deployment.status!=="deploying")throw Object.assign(new Error("Worker does not own this deployment."),{status:403});const artifact=await this.getArtifact(deployment.artifactId);const at=this.at();if(input.outcome==="unknown"){const uncertain=await this.repository.updateArtifactDeployment(id,this.teamId,{status:"outcome_unknown",uncertainAt:at,errorMetadata:input.errorMetadata||{},updatedAt:at},"deploying");await this.exception({exceptionType:"artifact_deployment_unknown",sourceEntityType:"artifact_deployment",sourceEntityId:id,summary:"Deployment outcome is unknown and must be verified before retry.",details:{artifactId:artifact.id}});return uncertain;}if(input.outcome==="failed"){const failed=await this.repository.updateArtifactDeployment(id,this.teamId,{status:"deployment_failed",errorMetadata:input.errorMetadata||{},completedAt:at,updatedAt:at},"deploying");await this.exception({exceptionType:"artifact_deployment_failed",sourceEntityType:"artifact_deployment",sourceEntityId:id,summary:"Artifact deployment failed and requires review.",details:{artifactId:artifact.id,...(input.errorMetadata||{})}});return failed;}if(input.verified!==true||input.deployedChecksum!==artifact.contentChecksum)throw Object.assign(new Error("Deployment verification does not match the approved artifact checksum."),{status:409});const url=required(input.deploymentUrl,"deploymentUrl");const done=await this.repository.updateArtifactDeployment(id,this.teamId,{status:"deployed",deploymentReference:String(input.deploymentReference||""),deploymentUrl:url,deployedChecksum:input.deployedChecksum,verificationResults:input.verificationResults||{verified:true},completedAt:at,updatedAt:at},"deploying");await this.repository.updateArtifactDeploymentFields(artifact.id,this.teamId,{deploymentTarget:deployment.targetId,deploymentUrl:url,status:"deployed",updatedAt:at});const job=await this.getJob(artifact.generationJobId);await this.repository.updateGenerationJob(job.id,this.teamId,{status:"deployed",updatedAt:at},["approved","deploy_queued","deploying"]);await this.activity({tenantId:artifact.tenantId,companyId:artifact.companyId,opportunityId:artifact.opportunityId,actorType:"service",actorId:worker.id,activityType:"artifact_deployed",summary:`Verified ${artifact.kind} deployment.`,metadata:{artifactId:artifact.id,deploymentId:id,deploymentUrl:url,contentChecksum:artifact.contentChecksum}});return done;}
  async attachArtifactToMessage(messageId,artifactId){role(this.actor,["owner","admin","sales"]);const message=await this.repository.getMessage(messageId,this.teamId);if(!message)throw Object.assign(new Error("Message not found."),{status:404});const artifact=await this.getArtifact(artifactId);if(artifact.status!=="deployed"||!artifact.deploymentUrl)throw Object.assign(new Error("Only an approved, deployed artifact version can be attached."),{status:409});if(message.opportunityId&&artifact.opportunityId!==message.opportunityId)throw Object.assign(new Error("Artifact and Message must belong to the same Opportunity."),{status:409});const at=this.at();const link=await this.repository.createMessageArtifact({id:this.idFactory("messageArtifact"),teamId:this.teamId,messageId,artifactId,artifactVersion:Number(artifact.versionNumber||artifact.version||1),artifactKind:artifact.kind,artifactTitle:artifact.metadata?.title||artifact.slug,deploymentUrlSnapshot:artifact.deploymentUrl,contentChecksum:artifact.contentChecksum,attachedBy:this.actor.id||"",attachedAt:at});await this.repository.updateMessage(messageId,this.teamId,{status:"draft",queueState:"not_queued",approvedSubject:"",approvedBody:"",approvedContentHash:"",approvedRecipientEmail:"",approvedSenderEmail:"",approvedBy:"",approvedAt:"",personalizationContext:{...(message.personalizationContext||{}),artifact:{id:artifact.id,version:Number(artifact.versionNumber||1),kind:artifact.kind,title:link.artifactTitle,url:link.deploymentUrlSnapshot,contentChecksum:artifact.contentChecksum}},updatedAt:at});await this.activity({tenantId:message.tenantId,companyId:artifact.companyId,contactId:message.contactId,opportunityId:artifact.opportunityId,campaignId:message.campaignId,messageId,activityType:"artifact_attached_to_message",summary:`Attached ${artifact.kind} ${artifact.slug} v${link.artifactVersion}; message approval invalidated.`,metadata:{artifactId,artifactVersion:link.artifactVersion,deploymentUrl:link.deploymentUrlSnapshot}});return link;}
}
