#!/usr/bin/env bash
# Regenerate the deck gallery (site/pitch/index.html) by scanning deck folders.
# Run after adding/removing decks. Skips the gallery, 404, and asset folders.
set -euo pipefail
root="$(cd "$(dirname "$0")/.." && pwd)"
pitch="$root/site/pitch"
out="$pitch/index.html"

cards=""
for d in "$pitch"/*/; do
  name="$(basename "$d")"
  case "$name" in assets|_assets) continue;; esac
  [ -f "$d/index.html" ] || continue
  title="$(printf '%s' "$name" | tr '-' ' ')"
  cards="$cards      <a class=\"card\" href=\"/$name/\"><span class=\"dot\"></span><div><h3>$title</h3><p>pitch.dgtlmedia.io/$name/</p></div><span class=\"arrow\">&rarr;</span></a>\n"
done

{
cat <<'HEAD'
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="noindex, nofollow">
<title>DGTL · Pitch Deck Index</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;600;700;800&display=swap" rel="stylesheet">
<style>
  :root{--bg:#0A0A0A;--gold:#F0CF50;--ink:#EDEDED;--dim:#9A9A9A;--card:#141414;--line:#242424}
  *{box-sizing:border-box}
  body{margin:0;background:var(--bg);color:var(--ink);font-family:Manrope,system-ui,sans-serif;padding:64px 24px}
  .wrap{max-width:760px;margin:0 auto}
  .kicker{color:var(--gold);font-weight:700;letter-spacing:.18em;text-transform:uppercase;font-size:12px}
  h1{font-size:34px;font-weight:800;margin:8px 0 4px}
  .sub{color:var(--dim);margin:0 0 32px}
  .card{display:flex;align-items:center;gap:16px;background:var(--card);border:1px solid var(--line);border-radius:14px;padding:18px 20px;margin-bottom:12px;text-decoration:none;color:var(--ink);transition:border-color .15s,transform .15s}
  .card:hover{border-color:var(--gold);transform:translateY(-2px)}
  .card h3{margin:0;font-size:18px;text-transform:capitalize}
  .card p{margin:2px 0 0;color:var(--dim);font-size:13px}
  .card .dot{width:10px;height:10px;border-radius:50%;background:var(--gold);flex:0 0 auto}
  .card>div{flex:1}
  .arrow{color:var(--gold);font-size:20px}
  footer{color:var(--dim);font-size:12px;margin-top:28px}
</style>
</head>
<body>
  <div class="wrap">
    <p class="kicker">DGTL Group · Internal</p>
    <h1>Pitch Decks</h1>
    <p class="sub">Every live deck under pitch.dgtlmedia.io. Auto-generated — run build-index.sh.</p>
HEAD
printf "%b" "$cards"
cat <<'FOOT'
    <footer>Generated by scripts/build-index.sh</footer>
  </div>
</body>
</html>
FOOT
} > "$out"

echo "wrote $out"
