import { Pool } from "pg";
import { PostgresStage3Repository } from "../stage3/repository.js";

function camelKey(key){return key.replace(/_([a-z])/g,(_,letter)=>letter.toUpperCase());}
function mapRow(row){return row?Object.fromEntries(Object.entries(row).map(([key,value])=>[camelKey(key),value?.toISOString?.()||value])):null;}
const json=(value)=>JSON.stringify(value??{});

export class PostgresStage4Repository extends PostgresStage3Repository {
  async transaction(work){if(!this.db.connect)return work(this);const client=await this.db.connect();try{await client.query("begin");const result=await work(new PostgresStage4Repository(client));await client.query("commit");return result;}catch(error){await client.query("rollback");throw error;}finally{client.release();}}
  async createIntegrationOperation(r){const existing=await this.findIntegrationOperationByIdempotency(r.teamId,r.idempotencyKey);if(existing)return existing;return mapRow((await this.db.query(`insert into integration_operations(id,team_id,tenant_id,connector_id,action,local_entity_type,local_entity_id,payload,payload_checksum,status,idempotency_key,requested_by,requested_at,attempt_count,result_metadata,error_metadata,created_at,updated_at) values($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11,$12,$13,$14,$15::jsonb,$16::jsonb,$17,$18) returning *`,[r.id,r.teamId,r.tenantId||null,r.connectorId,r.action,r.localEntityType,r.localEntityId,json(r.payload),r.payloadChecksum||null,r.status,r.idempotencyKey,r.requestedBy||null,r.requestedAt,r.attemptCount||0,json(r.resultMetadata),json(r.errorMetadata),r.createdAt,r.updatedAt])).rows[0]);}
  async getIntegrationOperation(id,teamId){return mapRow((await this.db.query("select * from integration_operations where id=$1 and team_id=$2",[id,teamId])).rows[0]);}
  async findIntegrationOperationByIdempotency(teamId,key){return mapRow((await this.db.query("select * from integration_operations where team_id=$1 and idempotency_key=$2",[teamId,key])).rows[0]);}
  async listIntegrationOperations(teamId,{status="",connectorId="",localEntityType="",localEntityId=""}={}){const clauses=["team_id=$1"];const args=[teamId];const add=(sql,value)=>{args.push(value);clauses.push(`${sql}=$${args.length}`);};if(status)if(Array.isArray(status)){args.push(status);clauses.push(`status=any($${args.length}::text[])`);}else add("status",status);if(connectorId)add("connector_id",connectorId);if(localEntityType)add("local_entity_type",localEntityType);if(localEntityId)add("local_entity_id",localEntityId);return(await this.db.query(`select * from integration_operations where ${clauses.join(" and ")} order by created_at desc`,args)).rows.map(mapRow);}
  async updateIntegrationOperation(id,teamId,values,expectedStatus){const columns={status:"status",payloadChecksum:"payload_checksum",approvedBy:"approved_by",approvedAt:"approved_at",attemptCount:"attempt_count",externalResultType:"external_result_type",externalResultId:"external_result_id",resultMetadata:"result_metadata",errorMetadata:"error_metadata",uncertainAt:"uncertain_at",startedAt:"started_at",completedAt:"completed_at",updatedAt:"updated_at"};const jsonFields=new Set(["resultMetadata","errorMetadata"]);const entries=Object.entries(values).filter(([key])=>columns[key]);if(!entries.length)return null;const args=entries.map(([key,value])=>jsonFields.has(key)?json(value):(value===""?null:value));const set=entries.map(([key],i)=>`${columns[key]}=$${i+1}${jsonFields.has(key)?"::jsonb":""}`).join(",");args.push(id,teamId);let where="";if(expectedStatus){args.push([].concat(expectedStatus));where=` and status=any($${args.length}::text[])`;}return mapRow((await this.db.query(`update integration_operations set ${set} where id=$${entries.length+1} and team_id=$${entries.length+2}${where} returning *`,args)).rows[0]);}
  async getExternalLinkById(id,teamId){return mapRow((await this.db.query("select * from external_links where id=$1 and team_id=$2",[id,teamId])).rows[0]);}
  async listExternalLinksForEntity(teamId,localEntityType,localEntityId,externalSystem=""){const args=[teamId,localEntityType,localEntityId];let where="team_id=$1 and local_entity_type=$2 and local_entity_id=$3";if(externalSystem){args.push(externalSystem);where+=` and external_system=$${args.length}`;}return(await this.db.query(`select * from external_links where ${where} order by updated_at desc`,args)).rows.map(mapRow);}
  async listExternalLinksBySystem(teamId,externalSystem,{externalObjectType="",externalId="",syncState="",localEntityType=""}={}){const clauses=["team_id=$1","external_system=$2"];const args=[teamId,externalSystem];const add=(sql,value)=>{args.push(value);clauses.push(`${sql}=$${args.length}`);};if(externalObjectType)add("external_object_type",externalObjectType);if(externalId)add("external_id",externalId);if(syncState)add("sync_state",syncState);if(localEntityType)add("local_entity_type",localEntityType);return(await this.db.query(`select * from external_links where ${clauses.join(" and ")} order by updated_at desc`,args)).rows.map(mapRow);}
  async updateExternalLink(id,teamId,values,expectedSyncState){const columns={externalUrl:"external_url",syncCursor:"sync_cursor",syncState:"sync_state",metadata:"metadata",linkedBy:"linked_by",linkedAt:"linked_at",lastVerifiedAt:"last_verified_at",lastVerifiedState:"last_verified_state",statusSnapshot:"status_snapshot",snapshotAt:"snapshot_at",linkHistory:"link_history",updatedAt:"updated_at"};const jsonFields=new Set(["metadata","statusSnapshot","linkHistory"]);const entries=Object.entries(values).filter(([key])=>columns[key]);if(!entries.length)return null;const args=entries.map(([key,value])=>jsonFields.has(key)?JSON.stringify(value??(key==="linkHistory"?[]:{})):(value===""?null:value));const set=entries.map(([key],i)=>`${columns[key]}=$${i+1}${jsonFields.has(key)?"::jsonb":""}`).join(",");args.push(id,teamId);let where="";if(expectedSyncState){args.push([].concat(expectedSyncState));where=` and sync_state=any($${args.length}::text[])`;}return mapRow((await this.db.query(`update external_links set ${set} where id=$${entries.length+1} and team_id=$${entries.length+2}${where} returning *`,args)).rows[0]);}
}

let pool;
export function getStage4Repository(){if(!process.env.DATABASE_URL)return null;if(!pool)pool=new Pool({connectionString:process.env.DATABASE_URL});return new PostgresStage4Repository(pool);}
export function __resetStage4RepositoryForTests(){pool=null;}
