export const manualFundingProgramCategories = [
  {
    id: "ontario-digital-adoption-planning",
    name: "Ontario Digital Adoption Planning",
    lane: "digital_adoption",
    region: "Ontario / Canada",
    eligibleBusinessTypes: ["Small and mid-sized businesses", "Retail", "Professional services", "Manufacturing"],
    eligibleExpenseTypes: ["Digital roadmap", "Website planning", "CRM planning", "Analytics setup"],
    typicalFundingRange: "Planning or advisory support; amount varies by program and intake.",
    matchSignals: ["digital", "website", "analytics", "software", "modernization", "online"],
    disqualificationSignals: ["No clear digital need", "No available project owner", "No implementation capacity"],
    dgtlServiceFit: "Fundable Project Blueprint and digital modernization roadmap.",
    nextStep: "Review the digital needs, budget, and province before naming any specific program.",
    sourceNotes: "Broad manual category only. Verify official program rules before client-facing claims.",
    sourceUrl: ""
  },
  {
    id: "ecommerce-modernization",
    name: "Ecommerce Modernization",
    lane: "ecommerce_growth",
    region: "Canada",
    eligibleBusinessTypes: ["Retail", "Consumer goods", "Food and beverage", "Beauty", "Apparel"],
    eligibleExpenseTypes: ["E-commerce improvements", "Conversion optimization", "Digital merchandising", "Paid acquisition setup"],
    typicalFundingRange: "Project support varies; may require matching funds or reimbursement.",
    matchSignals: ["ecommerce", "e-commerce", "shopify", "online sales", "conversion", "paid ads"],
    disqualificationSignals: ["No online sales channel", "No e-commerce growth goal", "No project budget"],
    dgtlServiceFit: "E-commerce growth blueprint, conversion plan, and campaign execution scope.",
    nextStep: "Confirm platform, current sales, budget, and target growth outcome.",
    sourceNotes: "Broad opportunity category, not a live grant recommendation.",
    sourceUrl: ""
  },
  {
    id: "export-market-development",
    name: "Export Market Development",
    lane: "export_marketing",
    region: "Canada / International markets",
    eligibleBusinessTypes: ["Manufacturing", "Food and beverage", "Technology", "Software", "Clean tech"],
    eligibleExpenseTypes: ["Market-entry assets", "Export marketing", "Trade content", "International campaign planning"],
    typicalFundingRange: "Often scoped around market-development activities; verify current funder rules.",
    matchSignals: ["export", "international", "us market", "global", "trade", "market entry"],
    disqualificationSignals: ["No target market", "No export interest", "No market-entry plan"],
    dgtlServiceFit: "Export-ready content, market-entry campaign plan, and application narrative.",
    nextStep: "Confirm target market, export status, timeline, and eligible activity rules.",
    sourceNotes: "Manual category only. Availability and eligibility require funder review.",
    sourceUrl: ""
  },
  {
    id: "creative-technology-market-development",
    name: "Creative Technology Market Development",
    lane: "creative_tech",
    region: "Canada",
    eligibleBusinessTypes: ["Creative studios", "Media companies", "Software teams", "Education technology"],
    eligibleExpenseTypes: ["Interactive content", "Video systems", "AR/VR prototypes", "Market launch assets"],
    typicalFundingRange: "Prototype, commercialization, or market-development support varies by source.",
    matchSignals: ["creative", "content", "media", "video", "ar", "vr", "interactive"],
    disqualificationSignals: ["No creative technology component", "No market-development objective"],
    dgtlServiceFit: "Creative technology prototype positioning and launch package.",
    nextStep: "Confirm the creative technology component and commercialization goal.",
    sourceNotes: "Category is broad and must be reviewed against current program definitions.",
    sourceUrl: ""
  },
  {
    id: "clean-tech-commercialization",
    name: "Clean-Tech Commercialization",
    lane: "clean_tech",
    region: "Canada",
    eligibleBusinessTypes: ["Clean tech", "Energy", "Manufacturing", "Construction", "Transportation"],
    eligibleExpenseTypes: ["Commercialization planning", "Market validation", "Sustainability communications", "Adoption campaigns"],
    typicalFundingRange: "Commercialization support varies significantly by technology and funder.",
    matchSignals: ["clean tech", "cleantech", "climate", "energy", "sustainability", "carbon", "retrofit"],
    disqualificationSignals: ["No clean-tech signal", "No commercialization path", "No technical evidence"],
    dgtlServiceFit: "Commercialization readiness narrative and market-entry materials.",
    nextStep: "Review technology readiness, customer proof, and target market.",
    sourceNotes: "No eligibility claim; official program criteria must be reviewed.",
    sourceUrl: ""
  },
  {
    id: "workforce-training",
    name: "Workforce Training",
    lane: "workforce_training",
    region: "Canada",
    eligibleBusinessTypes: ["Employers with team growth or systems adoption needs"],
    eligibleExpenseTypes: ["Training content", "Onboarding", "Upskilling", "Implementation enablement"],
    typicalFundingRange: "Training support may depend on employees, roles, providers, and timing.",
    matchSignals: ["training", "upskill", "enablement", "onboarding", "hiring", "staff"],
    disqualificationSignals: ["No employees", "No defined training need", "No adoption plan"],
    dgtlServiceFit: "Training and enablement content system tied to a growth project.",
    nextStep: "Confirm employee count, training objective, and implementation plan.",
    sourceNotes: "Manual category only; confirm current training program rules.",
    sourceUrl: ""
  },
  {
    id: "productivity-modernization",
    name: "Productivity Modernization",
    lane: "digital_adoption",
    region: "Canada",
    eligibleBusinessTypes: ["Manufacturing", "Construction", "Professional services", "Logistics"],
    eligibleExpenseTypes: ["Operational systems", "Workflow improvements", "Productivity tools", "Process documentation"],
    typicalFundingRange: "Usually depends on project scope, productivity impact, and eligible expenses.",
    matchSignals: ["productivity", "efficiency", "operations", "process", "systems", "modernization"],
    disqualificationSignals: ["No operational bottleneck", "No measurable productivity outcome"],
    dgtlServiceFit: "Operational modernization blueprint and implementation sprint.",
    nextStep: "Clarify the workflow problem, expected outcome, and measurement approach.",
    sourceNotes: "Broad category, not a confirmed funding match.",
    sourceUrl: ""
  },
  {
    id: "public-sector-creative-services-rfps",
    name: "Public-Sector Creative Services RFPs",
    lane: "public_procurement",
    region: "Canada",
    eligibleBusinessTypes: ["Creative agencies", "Technology firms", "Professional services", "Marketing teams"],
    eligibleExpenseTypes: ["Supplier profile", "Capability statement", "Case studies", "RFP response system"],
    typicalFundingRange: "Procurement opportunity value varies by buyer and RFP.",
    matchSignals: ["procurement", "government", "rfp", "supplier", "public sector", "municipal"],
    disqualificationSignals: ["No public-sector sales goal", "No supplier readiness", "No response capacity"],
    dgtlServiceFit: "Procurement readiness and supplier profile package.",
    nextStep: "Confirm target buyers, procurement history, and response capability.",
    sourceNotes: "RFP category only. No live procurement feed is connected.",
    sourceUrl: ""
  },
  {
    id: "website-crm-modernization",
    name: "Website/CRM Modernization",
    lane: "digital_adoption",
    region: "Canada",
    eligibleBusinessTypes: ["Service businesses", "Retail", "Health", "Construction", "Manufacturing"],
    eligibleExpenseTypes: ["Website rebuild", "CRM implementation", "Automation setup", "Measurement"],
    typicalFundingRange: "May be planning, implementation, or advisory support depending on program.",
    matchSignals: ["website", "crm", "automation", "pipeline", "customer lifecycle", "analytics"],
    disqualificationSignals: ["No website or CRM need", "No internal owner", "No adoption plan"],
    dgtlServiceFit: "Website, CRM, and automation blueprint with implementation milestones.",
    nextStep: "Confirm current stack, gaps, users, and desired business outcome.",
    sourceNotes: "Manual category only; eligibility must be verified later.",
    sourceUrl: ""
  },
  {
    id: "regional-business-growth",
    name: "Regional Business Growth",
    lane: "market_expansion",
    region: "Canadian regions / municipalities",
    eligibleBusinessTypes: ["Local SMEs", "Regional employers", "Main-street businesses", "Growth-stage firms"],
    eligibleExpenseTypes: ["Growth planning", "Local campaigns", "Digital assets", "Market development"],
    typicalFundingRange: "Regional support varies by jurisdiction and intake.",
    matchSignals: ["regional", "local", "new market", "growth", "campaign", "lead generation"],
    disqualificationSignals: ["No location detail", "No local growth objective", "No business traction"],
    dgtlServiceFit: "Regional growth funnel and campaign planning.",
    nextStep: "Confirm location, target market, and local program availability.",
    sourceNotes: "Broad regional category; official sources must be checked manually.",
    sourceUrl: ""
  },
  {
    id: "market-expansion",
    name: "Market Expansion",
    lane: "market_expansion",
    region: "Canada / selected external markets",
    eligibleBusinessTypes: ["Retail", "Professional services", "Technology", "Manufacturing", "Health"],
    eligibleExpenseTypes: ["Lead generation", "Sales funnel", "Market-entry campaign", "Customer acquisition assets"],
    typicalFundingRange: "Depends on region, project scope, and program rules.",
    matchSignals: ["market expansion", "new market", "lead generation", "sales", "growth", "campaign"],
    disqualificationSignals: ["No target market", "No sales capacity", "No measurable growth goal"],
    dgtlServiceFit: "Market expansion funnel and lead-generation campaign.",
    nextStep: "Confirm target customer, channel, budget, and expected outcome.",
    sourceNotes: "Potential category only; not a confirmed grant or program.",
    sourceUrl: ""
  },
  {
    id: "ai-workflow-automation-readiness",
    name: "AI/Workflow Automation Readiness",
    lane: "digital_adoption",
    region: "Canada",
    eligibleBusinessTypes: ["Service firms", "Technology-enabled SMEs", "Operations-heavy teams"],
    eligibleExpenseTypes: ["Workflow mapping", "AI readiness", "Automation design", "Training and adoption"],
    typicalFundingRange: "Readiness, advisory, or implementation support varies by program.",
    matchSignals: ["ai", "automation", "workflow", "process", "crm", "operations"],
    disqualificationSignals: ["No workflow pain", "No data/process owner", "No adoption capacity"],
    dgtlServiceFit: "AI/workflow automation readiness assessment and implementation scope.",
    nextStep: "Confirm workflow, data readiness, users, and risk controls.",
    sourceNotes: "Manual readiness category only. No AI funding claim is made.",
    sourceUrl: ""
  }
];

