#!/usr/bin/env python3
"""Generate journal/roster.html from the pack manifests.

The roster is the Journal's public creator directory — the first page that
actually consumes packs.index.json + each pack.json programmatically. It is
generated on the Mac and committed (static nginx serves the Journal; the
SEO-critical markup must exist at rest, not be client-rendered).

  python3 tools/build-roster.py              # rewrite journal/roster.html
  python3 tools/build-roster.py --check      # exit 1 if roster.html is stale
  python3 tools/build-roster.py --include-drafts

Run it after approving a new pack, changing any pack.json roster fields
(category / kicker / shortBio / avatar…), or editing this template. Then run
python3 tools/check-links.py as usual.
"""
import argparse
import html
import json
import os
import sys

REPO = os.path.normpath(os.path.join(os.path.dirname(__file__), ".."))
PACKS_DIR = os.path.join(REPO, "journal", "packs")
OUT = os.path.join(REPO, "journal", "roster.html")
BASE_URL = "https://dgtlinfluence.com"
JOIN_URL = "https://join.dgtlinfluence.com/"

CATEGORY_LABELS = {
    "music": "Music", "fashion": "Fashion", "sport": "Sport", "food": "Food",
    "tech": "Tech", "lifestyle": "Lifestyle", "comedy": "Comedy", "other": "Other",
}


def load_packs(include_drafts: bool):
    index = json.load(open(os.path.join(PACKS_DIR, "packs.index.json"), encoding="utf-8"))
    packs = []
    for slug in index["packs"]:
        manifest = os.path.join(PACKS_DIR, slug, "pack.json")
        if not os.path.exists(manifest):
            print(f"warn: {slug} listed in packs.index.json but has no pack.json — skipped", file=sys.stderr)
            continue
        p = json.load(open(manifest, encoding="utf-8"))
        if p.get("status") == "draft" and not include_drafts:
            print(f"note: {slug} is status=draft — excluded (pass --include-drafts to include)", file=sys.stderr)
            continue
        packs.append(p)
    return packs


def card(p: dict) -> str:
    slug = p["slug"]
    name = html.escape(p["name"])
    kicker = html.escape(p.get("kicker") or CATEGORY_LABELS.get(p.get("category", ""), ""))
    bio = html.escape(p.get("shortBio") or "")
    rt = html.escape(p.get("readTime") or "")
    cat = html.escape(p.get("category") or "other")

    if p.get("avatarImage"):
        src = f"packs/{slug}/{p['avatarImage']}"
        media = (f'<div class="media"><img src="{src}" alt="{name}" loading="lazy" '
                 'style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover">'
                 '<span class="flag">Creator</span></div>')
    elif p.get("avatarUrl"):
        media = (f'<div class="media"><img src="{html.escape(p["avatarUrl"])}" alt="{name}" loading="lazy" '
                 'style="position:absolute;inset:0;width:100%;height:100%;object-fit:cover">'
                 '<span class="flag">Creator</span></div>')
    else:
        ghost = html.escape(p.get("ghost") or name[:1])
        media = f'<div class="media ph-2"><span class="ghost">{ghost}</span><span class="flag">Creator</span></div>'

    return f'''      <a class="wcard reveal" href="packs/{slug}/index.html" data-category="{cat}">
        {media}
        <div class="c"><div class="eyebrow kicker">{kicker}</div><div class="t">{name}</div><div class="d">{bio}</div>
          <div class="foot"><span class="gold" style="font-weight:700;font-size:13px">Profile</span><span class="rt">{rt}</span></div></div>
      </a>'''


def render(packs) -> str:
    cats = sorted({p.get("category") for p in packs if p.get("category")})
    chips = ['      <button class="fpill active" data-roster-filter="all" aria-pressed="true">All</button>']
    chips += [
        f'      <button class="fpill" data-roster-filter="{c}" aria-pressed="false">{CATEGORY_LABELS.get(c, c.title())}</button>'
        for c in cats
    ]
    cards = "\n".join(card(p) for p in packs)

    item_list = ",\n        ".join(
        json.dumps({
            "@type": "ListItem", "position": i + 1,
            "name": p["name"],
            "url": p.get("canonicalUrl") or f"{BASE_URL}/packs/{p['slug']}/",
        }, ensure_ascii=False)
        for i, p in enumerate(packs)
    )

    n = len(packs)
    return f'''<!DOCTYPE html>
<!-- GENERATED by tools/build-roster.py — do not hand-edit. Re-run after pack changes. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>The DGTL Creator Roster — {n} Creators on the Influence Journal</title>
<meta name="description" content="The public roster of the DGTL Influence network: {n} vetted creators with published Journal profiles — filmmakers, artists, designers and more.">
<link rel="canonical" href="{BASE_URL}/roster.html">
<meta name="robots" content="index, follow, max-image-preview:large">
<meta property="og:type" content="website">
<meta property="og:site_name" content="DGTL Influence Journal">
<meta property="og:title" content="The DGTL Creator Roster">
<meta property="og:description" content="{n} vetted creators with published profiles on the DGTL Influence Journal.">
<meta property="og:url" content="{BASE_URL}/roster.html">
<meta name="twitter:card" content="summary_large_image">
<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;600;700;800&display=swap" rel="stylesheet">
<link rel="stylesheet" href="_shared/dgtl-editorial.css">
<link rel="icon" href="_shared/logos/spark.svg" type="image/svg+xml">
<script type="application/ld+json">
{{
  "@context": "https://schema.org",
  "@graph": [
    {{ "@type": "CollectionPage", "@id": "{BASE_URL}/roster.html#page",
      "name": "The DGTL Creator Roster", "url": "{BASE_URL}/roster.html",
      "isPartOf": {{ "@id": "{BASE_URL}/#website" }},
      "about": {{ "@id": "https://dgtlgroup.io/#organization" }} }},
    {{ "@type": "ItemList", "@id": "{BASE_URL}/roster.html#list",
      "numberOfItems": {n},
      "itemListElement": [
        {item_list}
      ] }}
  ]
}}
</script>
</head>
<body>

<header class="nav">
  <div class="nav-inner">
    <a class="nav-brand" href="index.html" aria-label="DGTL Influence Journal — home">
      <img class="wordmark" src="_shared/logos/logo-white-gold.svg" alt="DGTL" width="70" height="26">
      <span class="kicker">Influence Journal</span>
    </a>
    <nav class="nav-links" aria-label="Primary">
      <a href="index.html#creators">Creators</a>
      <a href="roster.html" aria-current="page">Roster</a>
      <a href="index.html#cases">Case Studies</a>
      <a href="https://dgtlgroup.io/about-us/">About</a>
      <a class="btn btn-primary btn-sm" href="{JOIN_URL}">Join the Roster →</a>
    </nav>
    <button class="nav-toggle" aria-label="Open menu"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M3 6h18M3 12h18M3 18h18"/></svg></button>
  </div>
</header>
<div class="nav-overlay" role="dialog" aria-modal="true" aria-label="Menu">
  <div class="bar">
    <img class="wordmark" src="_shared/logos/logo-white-gold.svg" alt="DGTL" width="70" height="26" style="height:25px">
    <button class="x" data-close aria-label="Close menu"><svg width="26" height="26" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M18 6 6 18M6 6l12 12"/></svg></button>
  </div>
  <a href="index.html#creators">Creators</a>
  <a href="roster.html">Roster</a>
  <a href="index.html#cases">Case Studies</a>
  <a href="https://dgtlgroup.io/about-us/">About</a>
  <a class="btn btn-primary" href="{JOIN_URL}">Join the Roster →</a>
</div>

<main>
  <section class="masthead wrap">
    <img class="spark-bg" src="_shared/logos/spark.svg" alt="" aria-hidden="true">
    <span class="eyebrow">The network, in public</span>
    <h1>The Creator <span class="gold">Roster</span></h1>
    <p class="sub">Every creator here holds a published, indexed profile on the Influence Journal —
    the people our brand partners book first.</p>
    <div class="chips" role="group" aria-label="Filter by category">
{chr(10).join(chips)}
    </div>
  </section>

  <section class="wrap section" id="roster" aria-label="Creator roster">
    <div class="grid-3" id="roster-grid">
{cards}
    </div>
  </section>

  <section class="wrap section" aria-label="Join">
    <div class="cta-band" style="border:1px solid var(--border);border-radius:var(--r-card);background:var(--surface-1);padding:48px;text-align:center">
      <span class="eyebrow">Applications open</span>
      <h2 style="margin:10px 0 8px">Your name belongs on this page.</h2>
      <p style="color:var(--text-dim);margin-bottom:24px">Ten minutes to apply — a published profile,
      a media-kit-grade feature, and campaign rotation if you're approved.</p>
      <a class="btn btn-primary" href="{JOIN_URL}">Join the roster</a>
    </div>
  </section>
</main>

<footer class="foot">
  <div class="wrap">
    <div class="top">
      <div class="brand">
        <img class="wordmark" src="_shared/logos/logo-white-gold.svg" alt="DGTL" width="70" height="26">
        <p>The Influence Journal — published by DGTL Influence, the specialised influencer arm of DGTL Group, Toronto.</p>
      </div>
      <div class="col"><h4>Journal</h4><a href="index.html#creators">Creators</a><a href="roster.html">Roster</a><a href="index.html#cases">Case Studies</a></div>
      <div class="col"><h4>Join</h4><a href="{JOIN_URL}">Apply as a creator</a><a href="{JOIN_URL}apply.html?type=brand">Apply as a brand</a><a href="{JOIN_URL}terms.html">Rights &amp; terms</a></div>
      <div class="col"><h4>DGTL</h4><a href="https://dgtlgroup.io/services/">Services</a><a href="https://dgtlgroup.io/work/">Work</a><a href="https://dgtlgroup.io/book-a-call">Book a Call</a></div>
    </div>
    <div class="base"><span>© 2026 DGTL. All Rights Reserved.</span><span>Toronto · Powered by DGTL Influence</span></div>
  </div>
</footer>

<script src="_shared/journal.js" defer></script>
<script>
// Category filter — roster-local so _shared/journal.js behavior stays untouched.
document.addEventListener('click', function (e) {{
  var btn = e.target.closest('[data-roster-filter]');
  if (!btn) return;
  var want = btn.dataset.rosterFilter;
  document.querySelectorAll('[data-roster-filter]').forEach(function (b) {{
    b.classList.toggle('active', b === btn);
    b.setAttribute('aria-pressed', b === btn ? 'true' : 'false');
  }});
  document.querySelectorAll('#roster-grid .wcard').forEach(function (card) {{
    card.style.display = (want === 'all' || card.dataset.category === want) ? '' : 'none';
  }});
}});
</script>
</body>
</html>
'''


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--check", action="store_true", help="exit 1 if roster.html is stale")
    ap.add_argument("--include-drafts", action="store_true")
    args = ap.parse_args()

    packs = load_packs(args.include_drafts)
    out = render(packs)

    if args.check:
        current = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
        if current != out:
            print("roster.html is STALE — re-run: python3 tools/build-roster.py")
            sys.exit(1)
        print("roster.html is current")
        return

    open(OUT, "w", encoding="utf-8").write(out)
    print(f"wrote journal/roster.html — {len(packs)} creators, categories: "
          + ", ".join(sorted({p.get('category', '?') for p in packs})))


if __name__ == "__main__":
    main()
