// DGTL Pass — the phone demo, in one command.
//
//   npm run demo:passes            start (or resume) the demo
//   npm run demo:passes -- --reset wipe the demo database and start fresh
//
// What it does, all on this Mac:
//   1. a Postgres 16 container just for the demo (dgtl-passes-demo, port 54329,
//      volume dgtl-passes-demo-data). Your dev database is never touched.
//   2. migrations, then the demo team, accounts, DGTL tenant and pass types
//   3. the platform on port 8090, reachable from a phone on the same Wi-Fi
//
// Secrets (database password, credential key, demo login password) are
// generated once into platform/data/passes-demo.env, which git ignores.
// Apple Wallet turns on when WALLETWALLET_API_KEY is in platform/.env
// (free key: https://www.walletwallet.dev/signup/).

import { execFileSync, spawn, spawnSync } from "node:child_process";
import crypto from "node:crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath } from "node:url";

const platformRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const dataDir = path.join(platformRoot, "data");
const envFile = path.join(dataDir, "passes-demo.env");
const CONTAINER = "dgtl-passes-demo";
const VOLUME = "dgtl-passes-demo-data";
const IMAGE = "postgres:16-alpine";
const DB_PORT = 54329;
const APP_PORT = Number(process.env.DEMO_PORT || 8090);
const reset = process.argv.includes("--reset");

const say = (line = "") => console.log(line);
const fail = (message) => {
  console.error(`\n[demo:passes] ${message}\n`);
  process.exit(1);
};

function docker(args, { quiet = false } = {}) {
  const result = spawnSync("docker", args, { encoding: "utf8" });
  if (result.status !== 0 && !quiet) fail(`docker ${args[0]} failed: ${(result.stderr || result.stdout).trim()}`);
  return result;
}

// ---- 1. secrets, generated once ----
function readEnvFile() {
  if (!existsSync(envFile)) return {};
  return Object.fromEntries(
    readFileSync(envFile, "utf8")
      .split("\n")
      .filter((line) => /^[A-Z_]+=/.test(line))
      .map((line) => [line.slice(0, line.indexOf("=")), line.slice(line.indexOf("=") + 1)])
  );
}
mkdirSync(dataDir, { recursive: true });
const saved = readEnvFile();
const secrets = {
  DEMO_DB_PASSWORD: saved.DEMO_DB_PASSWORD || crypto.randomBytes(18).toString("base64url"),
  PASS_CREDENTIAL_SECRETS: saved.PASS_CREDENTIAL_SECRETS || `demo1:${crypto.randomBytes(32).toString("base64")}`,
  PASS_CREDENTIAL_ACTIVE_KEY: saved.PASS_CREDENTIAL_ACTIVE_KEY || "demo1",
  PASSES_DEMO_PASSWORD: saved.PASSES_DEMO_PASSWORD || crypto.randomBytes(15).toString("base64url")
};
writeFileSync(
  envFile,
  `# DGTL Pass phone demo. Generated by scripts/demo-passes.mjs; git-ignored (platform/data/).\n# Never reuse these anywhere real.\n${Object.entries(secrets).map(([k, v]) => `${k}=${v}`).join("\n")}\n`,
  { mode: 0o600 }
);

// ---- 2. the demo database ----
if (spawnSync("docker", ["info"], { stdio: "ignore" }).status !== 0) fail("Docker is not running. Start Docker Desktop and try again.");
if (reset) {
  docker(["rm", "-f", CONTAINER], { quiet: true });
  docker(["volume", "rm", VOLUME], { quiet: true });
  say("[demo:passes] demo database wiped");
}
const state = docker(["inspect", "-f", "{{.State.Running}}", CONTAINER], { quiet: true });
if (state.status !== 0) {
  say(`[demo:passes] creating ${CONTAINER} (${IMAGE}, 127.0.0.1:${DB_PORT})`);
  docker([
    "run", "-d", "--name", CONTAINER,
    "-e", `POSTGRES_PASSWORD=${secrets.DEMO_DB_PASSWORD}`,
    "-e", "POSTGRES_DB=dgtl_passes_demo",
    "-p", `127.0.0.1:${DB_PORT}:5432`,
    "-v", `${VOLUME}:/var/lib/postgresql/data`,
    IMAGE
  ]);
} else if (state.stdout.trim() !== "true") {
  docker(["start", CONTAINER]);
}
for (let i = 0; ; i += 1) {
  if (docker(["exec", CONTAINER, "pg_isready", "-U", "postgres", "-d", "dgtl_passes_demo"], { quiet: true }).status === 0) break;
  if (i > 60) fail("Postgres did not become ready in 30 s.");
  await new Promise((resolve) => setTimeout(resolve, 500));
}

// ---- 3. where the phone finds this Mac ----
function lanAddress() {
  if (process.env.DEMO_HOST) return process.env.DEMO_HOST;
  const preferred = ["en0", "en1"];
  const all = Object.entries(os.networkInterfaces()).flatMap(([name, list]) => (list || []).map((entry) => ({ name, ...entry })));
  const candidates = all.filter((entry) => entry.family === "IPv4" && !entry.internal && /^(10|192\.168|172\.(1[6-9]|2\d|3[01]))\./.test(entry.address));
  candidates.sort((a, b) => (preferred.includes(a.name) ? -1 : 1) - (preferred.includes(b.name) ? -1 : 1));
  return candidates[0]?.address || "localhost";
}
const host = lanAddress();
const baseUrl = `http://${host}:${APP_PORT}`;
const env = {
  ...process.env,
  NODE_ENV: "development",
  DATABASE_URL: `postgres://postgres:${encodeURIComponent(secrets.DEMO_DB_PASSWORD)}@127.0.0.1:${DB_PORT}/dgtl_passes_demo`,
  PASS_PUBLIC_BASE_URL: baseUrl,
  PASS_ALLOWED_SCAN_HOSTS: "localhost",
  PASS_CREDENTIAL_SECRETS: secrets.PASS_CREDENTIAL_SECRETS,
  PASS_CREDENTIAL_ACTIVE_KEY: secrets.PASS_CREDENTIAL_ACTIVE_KEY,
  PASSES_DEMO_PASSWORD: secrets.PASSES_DEMO_PASSWORD,
  PUBLIC_APP_URL: baseUrl,
  NEXT_PUBLIC_APP_URL: baseUrl,
  NEXT_DEV_ALLOWED_ORIGINS: host
};

function run(script) {
  const result = spawnSync(process.execPath, [script], { cwd: platformRoot, env, stdio: "inherit" });
  if (result.status !== 0) fail(`${script} failed.`);
}
run("scripts/migrate.js");
run("scripts/seed-passes-dev.js");

// Wallet: read the settings the same way Next will (process env, then platform/.env).
const dotenv = existsSync(path.join(platformRoot, ".env")) ? readFileSync(path.join(platformRoot, ".env"), "utf8") : "";
const setting = (name) => process.env[name] || new RegExp(`^${name}=(.+)$`, "m").exec(dotenv)?.[1]?.trim() || "";
const appleCert = ["PASSKIT_TEAM_ID", "PASSKIT_PASS_TYPE_ID", "PASSKIT_SIGNER_CERT_B64", "PASSKIT_SIGNER_KEY_B64", "PASSKIT_WWDR_CERT_B64"].every(setting);
const provider = setting("PASS_WALLET_PROVIDER") || (appleCert ? "apple" : setting("WALLETWALLET_API_KEY") ? "walletwallet" : "");
const walletLine =
  provider === "apple"
    ? "ON  DGTL-signed: the exact DGTL design"
    : provider === "walletwallet"
      ? setting("WALLETWALLET_BRANDING") === "full"
        ? "ON  WalletWallet Pro: DGTL art, tier colours"
        : "ON  WalletWallet free: colour preset + text (WALLETWALLET_BRANDING=full on Pro)"
      : "OFF  add WALLETWALLET_API_KEY to platform/.env (free key at walletwallet.dev)";

say(`
  ┌──────────────────────────────────────────────────────────────────
  │  DGTL Pass demo
  │
  │  1. On this Mac     http://localhost:${APP_PORT}/admin/login
  │                     owner@passes-demo.test  → Passes → Issue pass
  │  2. On your iPhone  same Wi-Fi as this Mac. Point the camera at the
  │                     QR the Passes page shows: the pass opens.
  │  3. At the door     http://localhost:${APP_PORT}/scan on this Mac (live webcam),
  │                     or ${baseUrl}/scan on a second phone
  │                     door@passes-demo.test (photo scan over Wi-Fi)
  │
  │  Demo password      PASSES_DEMO_PASSWORD in platform/data/passes-demo.env
  │  Apple Wallet       ${walletLine}
  │  Pass links use     ${baseUrl}${host === "localhost" ? "   (no Wi-Fi address found: set DEMO_HOST)" : ""}
  └──────────────────────────────────────────────────────────────────
`);

// ---- 4. the platform ----
const next = spawn(process.platform === "win32" ? "npx.cmd" : "npx", ["next", "dev", "-p", String(APP_PORT), "-H", "0.0.0.0"], {
  cwd: platformRoot,
  env,
  stdio: "inherit"
});
const stop = () => {
  next.kill("SIGINT");
  try {
    execFileSync("docker", ["stop", CONTAINER], { stdio: "ignore" });
  } catch {
    // already stopped
  }
  process.exit(0);
};
process.on("SIGINT", stop);
process.on("SIGTERM", stop);
next.on("exit", (code) => {
  try {
    execFileSync("docker", ["stop", CONTAINER], { stdio: "ignore" });
  } catch {
    // already stopped
  }
  process.exit(code ?? 0);
});
