import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Pool } from "pg";
import { PostgresStage3Repository } from "../lib/stage3/repository.js";
import { ArtifactAutomationService } from "../lib/stage3/service.js";
import { commitWorkspaceCandidate, createIsolatedGitWorkspace, generateTemplatePitch, recordWorkspaceDiff, validateGeneratedPitch } from "../lib/stage3/isolatedPitchWorker.js";
import { persistLocalPreview } from "../lib/stage3/localPreview.js";

const parsed=new URL(process.env.DATABASE_URL||"http://invalid");
if(process.env.STAGE3_REHEARSAL_CONFIRM!=="isolated"||!["127.0.0.1","localhost"].includes(parsed.hostname))throw new Error("Stage 3 rehearsal only runs with STAGE3_REHEARSAL_CONFIRM=isolated against localhost.");
const platformRoot=path.join(path.dirname(fileURLToPath(import.meta.url)),"..");const repoRoot=path.join(platformRoot,"..");const baselineCommit=execFileSync("git",["rev-parse","HEAD"],{cwd:repoRoot,encoding:"utf8"}).trim();
const pool=new Pool({connectionString:process.env.DATABASE_URL});const repository=new PostgresStage3Repository(pool);const worker={id:"stage3-acceptance-worker"};let workspace1,workspace2;
const sales=new ArtifactAutomationService({teamId:"team_stage3",actor:{id:"sales_stage3",role:"sales"},repository,sourceCommit:baselineCommit});
const owner=new ArtifactAutomationService({teamId:"team_stage3",actor:{id:"owner_stage3",role:"owner"},repository,sourceCommit:baselineCommit});
try{
  await pool.query("insert into teams(id,name,slug) values('team_stage3','Stage 3 Rehearsal','stage3-rehearsal') on conflict do nothing");
  await pool.query("insert into tenants(id,slug,domains,status,config,team_id) values('tenant_stage3','stage3','[]','active','{}','team_stage3') on conflict do nothing");
  await pool.query(`insert into companies(id,team_id,tenant_id,display_name,normalized_domain,website_url,industry,city,country,relationship_status,source) values('company_stage3','team_stage3','tenant_stage3','Northstar Fabrication','northstar.test','https://northstar.test','Manufacturing','Toronto','CA','prospect','stage3_fixture') on conflict do nothing`);
  await pool.query(`insert into contacts(id,team_id,tenant_id,company_id,first_name,last_name,full_name,title,email,normalized_email,source) values('contact_stage3','team_stage3','tenant_stage3','company_stage3','Nora','Buyer','Nora Buyer','VP Growth','nora@northstar.test','nora@northstar.test','stage3_fixture') on conflict do nothing`);
  await pool.query(`insert into opportunities(id,team_id,tenant_id,company_id,primary_contact_id,name,stage,status,approach_angle,entry_offer,offer,source) values('opportunity_stage3','team_stage3','tenant_stage3','company_stage3','contact_stage3','Northstar digital overhaul','qualified','open','Lead with the gap between Northstar''s industrial credibility and its dated web presence.','Digital presence teardown','Website and systems overhaul','stage3_fixture') on conflict do nothing`);
  await pool.query(`insert into opportunity_contacts(opportunity_id,contact_id,role,is_primary,team_id) values('opportunity_stage3','contact_stage3','decision_maker',true,'team_stage3') on conflict do nothing`);
  await pool.query(`insert into research_records(id,team_id,tenant_id,company_id,opportunity_id,source_url,source_type,content,signal_category,captured_at,author_type,confidence,verification_status) values('research_stage3','team_stage3','tenant_stage3','company_stage3','opportunity_stage3','https://northstar.test/capabilities','website','Northstar publishes a multi-province fabrication capability list.','market_signal',now(),'user','high','verified') on conflict do nothing`);
  await pool.query(`insert into messages(id,team_id,tenant_id,opportunity_id,contact_id,channel,direction,subject,body,status,recipient_email,sender_email,rendered_subject,rendered_body,content_hash,approved_subject,approved_body,approved_content_hash,approved_recipient_email,approved_sender_email,approved_by,approved_at,queue_state,personalization_context) values('message_stage3','team_stage3','tenant_stage3','opportunity_stage3','contact_stage3','email','outbound','Northstar idea','Original copy','approved','nora@northstar.test','test@dgtl.invalid','Northstar idea','Original copy','old','Northstar idea','Original copy','old','nora@northstar.test','test@dgtl.invalid','owner_stage3',now(),'not_queued','{}') on conflict do nothing`);

  const job1=await sales.requestGeneration({opportunityId:"opportunity_stage3",artifactKind:"pitch",adapterId:"pitch.pages",slug:"northstar-stage3-acceptance",selectedResearchIds:["research_stage3"],instructions:"Use only verified research as factual claims.",intendedCta:"Book a discovery call"});await sales.approveInput(job1.id);const claimed1=await owner.claimJob(worker);assert.equal(claimed1.id,job1.id);
  workspace1=await createIsolatedGitWorkspace(repoRoot,baselineCommit);const output1=await generateTemplatePitch(claimed1,{workspaceRoot:workspace1.path});const diff1=recordWorkspaceDiff(workspace1.path,output1.paths);const validated1=await validateGeneratedPitch(claimed1,{workspaceRoot:workspace1.path,outputManifest:output1});const preview1=await persistLocalPreview(claimed1,{workspaceRoot:workspace1.path,outputManifest:validated1.outputManifest});const commit1=commitWorkspaceCandidate(workspace1.path,claimed1.slug);validated1.outputManifest.sourceCommit=commit1;await owner.submitResult(claimed1.id,worker,{...validated1,executionReference:`git-worktree:${workspace1.path}`,previewReference:preview1.reference,resultMetadata:{baselineCommit,diff:diff1,previewBytes:preview1.bytes}});let duplicateResultBlocked=false;try{await owner.submitResult(claimed1.id,worker,{...validated1});}catch{duplicateResultBlocked=true;}assert.equal(duplicateResultBlocked,true);
  const v1=await owner.approveArtifact(claimed1.id);const deployment1=await owner.requestDeployment(v1.id);await owner.claimDeployment(worker);await owner.completeDeployment(deployment1.id,worker,{verified:true,deployedChecksum:v1.contentChecksum,deploymentUrl:"https://preview.invalid/northstar-stage3-acceptance/v1/",deploymentReference:"isolated-preview-v1",verificationResults:{status:200,checksumMatched:true,production:false}});const attached=await sales.attachArtifactToMessage("message_stage3",v1.id);

  const job2=await sales.requestRevision(v1.id,"Move the verified capability proof above the offer section.");await sales.approveInput(job2.id);const claimed2=await owner.claimJob(worker);workspace2=await createIsolatedGitWorkspace(repoRoot,baselineCommit);const output2=await generateTemplatePitch(claimed2,{workspaceRoot:workspace2.path});const diff2=recordWorkspaceDiff(workspace2.path,output2.paths);const validated2=await validateGeneratedPitch(claimed2,{workspaceRoot:workspace2.path,outputManifest:output2});const preview2=await persistLocalPreview(claimed2,{workspaceRoot:workspace2.path,outputManifest:validated2.outputManifest});const commit2=commitWorkspaceCandidate(workspace2.path,claimed2.slug);validated2.outputManifest.sourceCommit=commit2;await owner.submitResult(claimed2.id,worker,{...validated2,executionReference:`git-worktree:${workspace2.path}`,previewReference:preview2.reference,resultMetadata:{baselineCommit,diff:diff2,previewBytes:preview2.bytes}});const v2=await owner.approveArtifact(claimed2.id);
  const links=await repository.listMessageArtifacts("message_stage3","team_stage3");const message=await repository.getMessage("message_stage3","team_stage3");assert.equal(v1.versionNumber,1);assert.equal(v2.versionNumber,2);assert.notEqual(v1.contentChecksum,v2.contentChecksum);assert.equal(links.length,1);assert.equal(links[0].artifactId,v1.id);assert.equal(attached.deploymentUrlSnapshot,"https://preview.invalid/northstar-stage3-acceptance/v1/");assert.equal(message.status,"draft");assert.equal((await repository.listArtifacts("team_stage3")).length,2);
  console.log(JSON.stringify({isolated:true,productionDeployment:false,externalEmailSent:false,baselineCommit,adapter:claimed1.adapterId,skill:claimed1.requestedSkill,contextResearch:claimed1.contextSnapshot.research.map(item=>({id:item.id,provenanceClass:item.provenanceClass})),v1:{id:v1.id,version:v1.versionNumber,checksum:v1.contentChecksum,sourceCommit:commit1,previewReference:preview1.reference,previewBytes:preview1.bytes,deploymentUrl:attached.deploymentUrlSnapshot,diff:diff1},v2:{id:v2.id,version:v2.versionNumber,checksum:v2.contentChecksum,sourceCommit:commit2,previewReference:preview2.reference,previewBytes:preview2.bytes,previousVersionId:v2.previousVersionId,diff:diff2},message:{id:message.id,status:message.status,attachedArtifactId:links[0].artifactId,attachedVersion:links[0].artifactVersion},duplicateResultBlocked,artifactCount:2,activityCount:(await repository.getOpportunityGraph("opportunity_stage3","team_stage3")).activities.length},null,2));
}finally{if(workspace1)await workspace1.cleanup().catch(()=>{});if(workspace2)await workspace2.cleanup().catch(()=>{});await pool.end();}
